RUN {
  BACKUP AS COMPRESSED BACKUPSET DATABASE PLUS ARCHIVELOG NOT BACKED UP 1 TIMES SKIP INACCESSIBLE;
  DELETE FORCE NOPROMPT OBSOLETE;
  DELETE FORCE NOPROMPT BACKUPSET COMPLETED BEFORE 'sysdate-3';
}

EXIT;
