#!/bin/bash

# Set environment
. /home/oracle/.bash_profile

rman target sys/$db_pass <<!
SELECT CAST(TO_CHAR(SYSDATE,'DD-MM-YYYY HH24:MI:SS') AS VARCHAR2(30)) AS CROSSCHECK_STEP_1 FROM DUAL;
CROSSCHECK BACKUP;
REPORT OBSOLETE;
LIST EXPIRED BACKUP;
SELECT CAST(TO_CHAR(SYSDATE,'DD-MM-YYYY HH24:MI:SS') AS VARCHAR2(30)) AS DELETE_STEP_2 FROM DUAL;
DELETE NOPROMPT OBSOLETE;
DELETE NOPROMPT EXPIRED BACKUP;
DELETE NOPROMPT ARCHIVELOG ALL BACKED UP 1 TIMES TO 'SBT_TAPE';
DELETE NOPROMPT BACKUP OF ARCHIVELOG UNTIL TIME 'SYSDATE-5';
DELETE NOPROMPT ARCHIVELOG ALL COMPLETED BEFORE 'SYSDATE-5';
DELETE NOPROMPT BACKUP OF CONTROLFILE COMPLETED BEFORE 'SYSDATE-7';
SELECT CAST(TO_CHAR(SYSDATE,'DD-MM-YYYY HH24:MI:SS') AS VARCHAR2(30)) AS RESTORE_STEP_3 FROM DUAL;
# see SR 3-15869076511, Doc ID 1554636.1, the restore preview will list all backups required for the entire restore and recovery operation
RESTORE DATABASE PREVIEW;
SELECT CAST(TO_CHAR(SYSDATE,'DD-MM-YYYY HH24:MI:SS') AS VARCHAR2(30)) AS SUMMARY_STEP_4 FROM DUAL;
LIST BACKUP SUMMARY;
exit
!