--   Target database:	ARCHDB.raiffeisen.ru
--   Script generated at:	17-DEC-2014   11:11
COMMIT
ALTER SESSION ENABLE PARALLEL DML
CREATE TABLE "TCTDBS"."CARD_LISTING_SHORT$REORG" ( "SERNO" NUMBER(10),  "CARDNUMBER" CHAR(25),  "OTB" NUMBER(16, 3),  "SUM_OS" NUMBER(16, 3),  "LTIMESTAMP" DATE) TABLESPACE "ONLDATA_ENC" PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE  ( INITIAL 64K BUFFER_POOL DEFAULT)  LOGGING  PARALLEL  ENABLE ROW MOVEMENT 
COMMIT
BEGIN DBMS_REDEFINITION.START_REDEF_TABLE('"TCTDBS"', '"CARD_LISTING_SHORT"', '"CARD_LISTING_SHORT$REORG"'); END;
CREATE UNIQUE  INDEX "TCTDBS"."CARD_LISTING_SHORT_PK$REORG" ON "TCTDBS"."CARD_LISTING_SHORT$REORG"  ("CARDNUMBER", "LTIMESTAMP") PARALLEL  TABLESPACE "ONLINDEX_ENC" PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE  ( INITIAL 64K BUFFER_POOL DEFAULT)  LOGGING  COMPRESS 1

BEGIN DBMS_REDEFINITION.REGISTER_DEPENDENT_OBJECT('"TCTDBS"', '"CARD_LISTING_SHORT"', '"CARD_LISTING_SHORT$REORG"', DBMS_REDEFINITION.CONS_INDEX, '"TCTDBS"', '"CARD_LISTING_SHORT_PK"', '"CARD_LISTING_SHORT_PK$REORG"'); END;
ALTER TABLE "TCTDBS"."CARD_LISTING_SHORT$REORG"  ADD ( CONSTRAINT "CARD_LISTING_SHORT_PK$REORG0" PRIMARY KEY ("CARDNUMBER", "LTIMESTAMP")  VALIDATE )
BEGIN DBMS_REDEFINITION.REGISTER_DEPENDENT_OBJECT('"TCTDBS"', '"CARD_LISTING_SHORT"', '"CARD_LISTING_SHORT$REORG"', DBMS_REDEFINITION.CONS_CONSTRAINT, '"TCTDBS"', '"CARD_LISTING_SHORT_PK"', '"CARD_LISTING_SHORT_PK$REORG0"'); END;
BEGIN DBMS_REDEFINITION.SYNC_INTERIM_TABLE('"TCTDBS"', '"CARD_LISTING_SHORT"', '"CARD_LISTING_SHORT$REORG"'); END;
BEGIN DBMS_STATS.GATHER_TABLE_STATS('"TCTDBS"', '"CARD_LISTING_SHORT$REORG"', estimate_percent=>NULL, degree=>DBMS_STATS.DEFAULT_DEGREE, cascade=>TRUE); END;
ALTER TABLE "TCTDBS"."CARD_LISTING_SHORT$REORG" PARALLEL 4
ALTER INDEX "TCTDBS"."CARD_LISTING_SHORT_PK$REORG" NOPARALLEL
BEGIN DBMS_REDEFINITION.FINISH_REDEF_TABLE('"TCTDBS"', '"CARD_LISTING_SHORT"', '"CARD_LISTING_SHORT$REORG"'); END;
DROP TABLE "TCTDBS"."CARD_LISTING_SHORT$REORG" CASCADE CONSTRAINTS PURGE
ALTER PACKAGE "TCTDBS"."IMPORT_FROM_ONLINE" COMPILE BODY