CREATE OR REPLACE PROCEDURE TRANS_LOAD_onldb02 (
   V_MIN_SERNO   IN NUMBER DEFAULT 0,
   V_MAX_SERNO   IN NUMBER DEFAULT 0)
IS
   --procedure is for insert data from authorizations table from V_MIN_SERNO to V_MAX_SERNO
   V_ROWS_INSERTED   NUMBER;
   v_code            NUMBER;
   v_eodserno        NUMBER;
   V_MAX_SERNO_AUTO  NUMBER;
   V_MIN_SERNO_AUTO  NUMBER;
   v_errm            VARCHAR2 (1000);
   v_type            VARCHAR2 (15);
   v_state           VARCHAR2 (15);
   v_cursor          BINARY_INTEGER;
   v_select          VARCHAR2 (200);
BEGIN
  
   DBMS_OUTPUT.ENABLE;
   
   -- determine the state of database, if it is primary then exit
   
   v_select := 'select state,type from sysmaster:sysdri;';
   v_cursor := DBMS_HS_PASSTHROUGH.open_cursor@onldb02;
   DBMS_HS_PASSTHROUGH.parse@onldb02(v_cursor, v_select);

   WHILE DBMS_HS_PASSTHROUGH.fetch_row@onldb02(v_cursor) > 0
   LOOP
      DBMS_HS_PASSTHROUGH.GET_VALUE@onldb02(v_cursor, 1, v_state);
      DBMS_HS_PASSTHROUGH.GET_VALUE@onldb02(v_cursor, 2, v_type);
   END LOOP;

   DBMS_OUTPUT.put_line('state ' || v_state);
   DBMS_OUTPUT.put_line('type ' || v_type);
   DBMS_HS_PASSTHROUGH.close_cursor@onldb02(v_cursor);

  IF v_type not in ('Secondary','Not Initialized')
   THEN
      RETURN;
   END IF;
   
   -- if DB is secondary then copy data from authorizations table

   SELECT MIN ("serno")
     INTO v_eodserno
     FROM "eods"@onldb02
    WHERE "serno" > (SELECT MAX (eodserno) FROM LOADED_EODS_TEST);

   IF (V_MIN_SERNO - V_MAX_SERNO) <> 0
   THEN
         INSERT /*+ PARALLEL(authorizations_test) */ INTO authorizations_test (serno,
                                                 ltimestamp,
                                                 processtimems,
                                                 groupfromserial,
                                                 grouptoserial,
                                                 extserno,
                                                 edcserno,
                                                 cardserno,
                                                 cardcurrency,
                                                 eodserno,
                                                 origserno,
                                                 source,
                                                 reasoncode,
                                                 otb_amt_center,
                                                 otb_amt_card,
                                                 amt_center,
                                                 amt_card,
                                                 orig_amt_center,
                                                 orig_amt_card,
                                                 safflag,
                                                 saftimestamp,
                                                 safretrycount,
                                                 batchno,
                                                 msgflags,
                                                 affectedotbs,
                                                 trxnserno,
                                                 matchtime,
                                                 transaction_id,
                                                 i000_msg_type,
                                                 i002_number,
                                                 i003_proc_code,
                                                 i004_amt_trxn,
                                                 i005_amt_settle,
                                                 i006_amt_bill,
                                                 i007_trans_dt,
                                                 i009_setl_conv,
                                                 i011_trace_num,
                                                 i012_lcl_time,
                                                 i013_lcl_dt,
                                                 i014_exp_date,
                                                 i016_conv_dt,
                                                 i018_merch_type,
                                                 i019_acq_country,
                                                 i021_fwd_cntry,
                                                 i022_pos_entry,
                                                 i023_card_seq_num,
                                                 i024_int_netwk_id,
                                                 i025_pos_cond,
                                                 i026_accptr_buscd,
                                                 i028_transfer_fee,
                                                 i029_setl_fee,
                                                 i030_trsf_prc_fee,
                                                 i031_setl_proc_fee,
                                                 i032_acquirer_id,
                                                 i033_forwarder_id,
                                                 i035_trk_2,
                                                 i037_ret_ref_num,
                                                 i038_auth_id,
                                                 i039_rsp_cd,
                                                 i041_pos_id,
                                                 i042_merch_id,
                                                 i043a_merch_name,
                                                 i043b_merch_city,
                                                 i043c_merch_cnt,
                                                 i044_addtnl_rsp,
                                                 i045_trk_1,
                                                 i048_text_data,
                                                 i049_cur_trxn,
                                                 i050_cur_settle,
                                                 i051_cur_bill,
                                                 i053_sec_cntrl,
                                                 i054_addtnl_amt,
                                                 i055_icc_data,
                                                 i056_org_data,
                                                 i059_pos_geo_data,
                                                 i060_pos_cap,
                                                 i061v1_oth_amt_txn,
                                                 i061v2_oth_amt_bil,
                                                 i061v3_rep_amt_bil,
                                                 i061m_pos_data,
                                                 i062v1_auth_char,
                                                 i062v2_trans_id,
                                                 i062v3_validat_cd,
                                                 i062v4_mrkt_data,
                                                 i062v5_duration,
                                                 i062v6_prstg_prop,
                                                 i063_banknet_data,
                                                 i063v1_network_id,
                                                 i063v2_time_limit,
                                                 i063v3_mis_cas_rd,
                                                 i063v4_stip_rs,
                                                 i063v5_pmc_id,
                                                 i068_rcv_cntry,
                                                 i090_orig_data,
                                                 i095_act_tran_amt,
                                                 i100_rcv_inst,
                                                 i102_acct_id1,
                                                 i103_acct_id2,
                                                 i118_intra_country,
                                                 i123_adr_ver,
                                                 i126v6_ch_cserial,
                                                 i126v7_me_cserial,
                                                 i126v8_trxn_id,
                                                 i126v9_stain,
                                                 i126v10_cvv2,
                                                 i126v13_pos_env,
                                                 i130_term_capa,
                                                 i131_tvr,
                                                 i132_unpredict,
                                                 i133_term_serial,
                                                 i134_visa_discr,
                                                 i135a_preauthtrace,
                                                 i135b_purchtrace,
                                                 i135c_crypttrace,
                                                 i135d_keyversion,
                                                 i136_cryptogram,
                                                 i137_atc,
                                                 i138_apl,
                                                 i139_1_arpc,
                                                 i139_2_arpc_rescd,
                                                 i142_scriptsend,
                                                 i143_script_res,
                                                 i144_cryp_tr,
                                                 i145_trm_cntry,
                                                 i146_trm_date,
                                                 i147_crypt_amt,
                                                 i148_crypt_curr,
                                                 i149_crypt_csbk)
            SELECT "serno",
                   "timestamp",
                   "processtimems",
                   "groupfromserial",
                   "grouptoserial",
                   "extserno",
                   "edcserno",
                   "cardserno",
                   "cardcurrency",
                   "eodserno",
                   "origserno",
                   "source",
                   "reasoncode",
                   "otb_amt_center",
                   "otb_amt_card",
                   "amt_center",
                   "amt_card",
                   "orig_amt_center",
                   "orig_amt_card",
                   "safflag",
                   "saftimestamp",
                   "safretrycount",
                   "batchno",
                   "msgflags",
                   "affectedotbs",
                   "trxnserno",
                   "matchtime",
                   "transaction_id",
                   "i000_msg_type",
                   "i002_number",
                   "i003_proc_code",
                   "i004_amt_trxn",
                   "i005_amt_settle",
                   "i006_amt_bill",
                   "i007_trans_dt",
                   "i009_setl_conv",
                   "i011_trace_num",
                   "i012_lcl_time",
                   "i013_lcl_dt",
                   "i014_exp_date",
                   "i016_conv_dt",
                   "i018_merch_type",
                   "i019_acq_country",
                   "i021_fwd_cntry",
                   "i022_pos_entry",
                   "i023_card_seq_num",
                   "i024_int_netwk_id",
                   "i025_pos_cond",
                   "i026_accptr_buscd",
                   "i028_transfer_fee",
                   "i029_setl_fee",
                   "i030_trsf_prc_fee",
                   "i031_setl_proc_fee",
                   "i032_acquirer_id",
                   "i033_forwarder_id",
                   "i035_trk_2",
                   "i037_ret_ref_num",
                   "i038_auth_id",
                   "i039_rsp_cd",
                   "i041_pos_id",
                   "i042_merch_id",
                   "i043a_merch_name",
                   "i043b_merch_city",
                   "i043c_merch_cnt",
                   "i044_addtnl_rsp",
                   "i045_trk_1",
                   "i048_text_data",
                   "i049_cur_trxn",
                   "i050_cur_settle",
                   "i051_cur_bill",
                   "i053_sec_cntrl",
                   "i054_addtnl_amt",
                   "i055_icc_data",
                   "i056_org_data",
                   "i059_pos_geo_data",
                   "i060_pos_cap",
                   "i061v1_oth_amt_txn",
                   "i061v2_oth_amt_bil",
                   "i061v3_rep_amt_bil",
                   "i061m_pos_data",
                   "i062v1_auth_char",
                   "i062v2_trans_id",
                   "i062v3_validat_cd",
                   "i062v4_mrkt_data",
                   "i062v5_duration",
                   "i062v6_prstg_prop",
                   "i063_banknet_data",
                   "i063v1_network_id",
                   "i063v2_time_limit",
                   "i063v3_mis_cas_rd",
                   "i063v4_stip_rs",
                   "i063v5_pmc_id",
                   "i068_rcv_cntry",
                   "i090_orig_data",
                   "i095_act_tran_amt",
                   "i100_rcv_inst",
                   "i102_acct_id1",
                   "i103_acct_id2",
                   "i118_intra_country",
                   "i123_adr_ver",
                   "i126v6_ch_cserial",
                   "i126v7_me_cserial",
                   "i126v8_trxn_id",
                   "i126v9_stain",
                   "i126v10_cvv2",
                   "i126v13_pos_env",
                   "i130_term_capa",
                   "i131_tvr",
                   "i132_unpredict",
                   "i133_term_serial",
                   "i134_visa_discr",
                   "i135a_preauthtrace",
                   "i135b_purchtrace",
                   "i135c_crypttrace",
                   "i135d_keyversion",
                   "i136_cryptogram",
                   "i137_atc",
                   "i138_apl",
                   "i139_1_arpc",
                   "i139_2_arpc_rescd",
                   "i142_scriptsend",
                   "i143_script_res",
                   "i144_cryp_tr",
                   "i145_trm_cntry",
                   "i146_trm_date",
                   "i147_crypt_amt",
                   "i148_crypt_curr",
                   "i149_crypt_csbk"
              FROM "authorizations"@onldb02
             WHERE "serno" BETWEEN V_MIN_SERNO AND V_MAX_SERNO;

         -- count number of rows inserted in the archive DB
         V_ROWS_INSERTED := SQL%ROWCOUNT;
         COMMIT;

         SELECT eodserno INTO v_eodserno FROM authorizations_test WHERE serno = V_MAX_SERNO;
         
         -- insert information about data transfer process into TCTDBS.LOADED_EODS table
         INSERT INTO LOADED_EODS_TEST (INSERT_DATE,
                                         MIN_SERNO,
                                         MAX_SERNO,
                                         ROWS_INSERTED,
                                         eodserno)
              VALUES (SYSDATE,
                      V_MIN_SERNO,
                      V_MAX_SERNO,
                      V_ROWS_INSERTED,
                      v_eodserno);

         DBMS_OUTPUT.put_line (V_ROWS_INSERTED || ' ROWS INSERTED');

         COMMIT;
      ELSE
         INSERT /*+ PARALLEL(authorizations_test) */ INTO authorizations_test (serno,
                                                 ltimestamp,
                                                 processtimems,
                                                 groupfromserial,
                                                 grouptoserial,
                                                 extserno,
                                                 edcserno,
                                                 cardserno,
                                                 cardcurrency,
                                                 eodserno,
                                                 origserno,
                                                 source,
                                                 reasoncode,
                                                 otb_amt_center,
                                                 otb_amt_card,
                                                 amt_center,
                                                 amt_card,
                                                 orig_amt_center,
                                                 orig_amt_card,
                                                 safflag,
                                                 saftimestamp,
                                                 safretrycount,
                                                 batchno,
                                                 msgflags,
                                                 affectedotbs,
                                                 trxnserno,
                                                 matchtime,
                                                 transaction_id,
                                                 i000_msg_type,
                                                 i002_number,
                                                 i003_proc_code,
                                                 i004_amt_trxn,
                                                 i005_amt_settle,
                                                 i006_amt_bill,
                                                 i007_trans_dt,
                                                 i009_setl_conv,
                                                 i011_trace_num,
                                                 i012_lcl_time,
                                                 i013_lcl_dt,
                                                 i014_exp_date,
                                                 i016_conv_dt,
                                                 i018_merch_type,
                                                 i019_acq_country,
                                                 i021_fwd_cntry,
                                                 i022_pos_entry,
                                                 i023_card_seq_num,
                                                 i024_int_netwk_id,
                                                 i025_pos_cond,
                                                 i026_accptr_buscd,
                                                 i028_transfer_fee,
                                                 i029_setl_fee,
                                                 i030_trsf_prc_fee,
                                                 i031_setl_proc_fee,
                                                 i032_acquirer_id,
                                                 i033_forwarder_id,
                                                 i035_trk_2,
                                                 i037_ret_ref_num,
                                                 i038_auth_id,
                                                 i039_rsp_cd,
                                                 i041_pos_id,
                                                 i042_merch_id,
                                                 i043a_merch_name,
                                                 i043b_merch_city,
                                                 i043c_merch_cnt,
                                                 i044_addtnl_rsp,
                                                 i045_trk_1,
                                                 i048_text_data,
                                                 i049_cur_trxn,
                                                 i050_cur_settle,
                                                 i051_cur_bill,
                                                 i053_sec_cntrl,
                                                 i054_addtnl_amt,
                                                 i055_icc_data,
                                                 i056_org_data,
                                                 i059_pos_geo_data,
                                                 i060_pos_cap,
                                                 i061v1_oth_amt_txn,
                                                 i061v2_oth_amt_bil,
                                                 i061v3_rep_amt_bil,
                                                 i061m_pos_data,
                                                 i062v1_auth_char,
                                                 i062v2_trans_id,
                                                 i062v3_validat_cd,
                                                 i062v4_mrkt_data,
                                                 i062v5_duration,
                                                 i062v6_prstg_prop,
                                                 i063_banknet_data,
                                                 i063v1_network_id,
                                                 i063v2_time_limit,
                                                 i063v3_mis_cas_rd,
                                                 i063v4_stip_rs,
                                                 i063v5_pmc_id,
                                                 i068_rcv_cntry,
                                                 i090_orig_data,
                                                 i095_act_tran_amt,
                                                 i100_rcv_inst,
                                                 i102_acct_id1,
                                                 i103_acct_id2,
                                                 i118_intra_country,
                                                 i123_adr_ver,
                                                 i126v6_ch_cserial,
                                                 i126v7_me_cserial,
                                                 i126v8_trxn_id,
                                                 i126v9_stain,
                                                 i126v10_cvv2,
                                                 i126v13_pos_env,
                                                 i130_term_capa,
                                                 i131_tvr,
                                                 i132_unpredict,
                                                 i133_term_serial,
                                                 i134_visa_discr,
                                                 i135a_preauthtrace,
                                                 i135b_purchtrace,
                                                 i135c_crypttrace,
                                                 i135d_keyversion,
                                                 i136_cryptogram,
                                                 i137_atc,
                                                 i138_apl,
                                                 i139_1_arpc,
                                                 i139_2_arpc_rescd,
                                                 i142_scriptsend,
                                                 i143_script_res,
                                                 i144_cryp_tr,
                                                 i145_trm_cntry,
                                                 i146_trm_date,
                                                 i147_crypt_amt,
                                                 i148_crypt_curr,
                                                 i149_crypt_csbk)
            SELECT "serno",
                   "timestamp",
                   "processtimems",
                   "groupfromserial",
                   "grouptoserial",
                   "extserno",
                   "edcserno",
                   "cardserno",
                   "cardcurrency",
                   "eodserno",
                   "origserno",
                   "source",
                   "reasoncode",
                   "otb_amt_center",
                   "otb_amt_card",
                   "amt_center",
                   "amt_card",
                   "orig_amt_center",
                   "orig_amt_card",
                   "safflag",
                   "saftimestamp",
                   "safretrycount",
                   "batchno",
                   "msgflags",
                   "affectedotbs",
                   "trxnserno",
                   "matchtime",
                   "transaction_id",
                   "i000_msg_type",
                   "i002_number",
                   "i003_proc_code",
                   "i004_amt_trxn",
                   "i005_amt_settle",
                   "i006_amt_bill",
                   "i007_trans_dt",
                   "i009_setl_conv",
                   "i011_trace_num",
                   "i012_lcl_time",
                   "i013_lcl_dt",
                   "i014_exp_date",
                   "i016_conv_dt",
                   "i018_merch_type",
                   "i019_acq_country",
                   "i021_fwd_cntry",
                   "i022_pos_entry",
                   "i023_card_seq_num",
                   "i024_int_netwk_id",
                   "i025_pos_cond",
                   "i026_accptr_buscd",
                   "i028_transfer_fee",
                   "i029_setl_fee",
                   "i030_trsf_prc_fee",
                   "i031_setl_proc_fee",
                   "i032_acquirer_id",
                   "i033_forwarder_id",
                   "i035_trk_2",
                   "i037_ret_ref_num",
                   "i038_auth_id",
                   "i039_rsp_cd",
                   "i041_pos_id",
                   "i042_merch_id",
                   "i043a_merch_name",
                   "i043b_merch_city",
                   "i043c_merch_cnt",
                   "i044_addtnl_rsp",
                   "i045_trk_1",
                   "i048_text_data",
                   "i049_cur_trxn",
                   "i050_cur_settle",
                   "i051_cur_bill",
                   "i053_sec_cntrl",
                   "i054_addtnl_amt",
                   "i055_icc_data",
                   "i056_org_data",
                   "i059_pos_geo_data",
                   "i060_pos_cap",
                   "i061v1_oth_amt_txn",
                   "i061v2_oth_amt_bil",
                   "i061v3_rep_amt_bil",
                   "i061m_pos_data",
                   "i062v1_auth_char",
                   "i062v2_trans_id",
                   "i062v3_validat_cd",
                   "i062v4_mrkt_data",
                   "i062v5_duration",
                   "i062v6_prstg_prop",
                   "i063_banknet_data",
                   "i063v1_network_id",
                   "i063v2_time_limit",
                   "i063v3_mis_cas_rd",
                   "i063v4_stip_rs",
                   "i063v5_pmc_id",
                   "i068_rcv_cntry",
                   "i090_orig_data",
                   "i095_act_tran_amt",
                   "i100_rcv_inst",
                   "i102_acct_id1",
                   "i103_acct_id2",
                   "i118_intra_country",
                   "i123_adr_ver",
                   "i126v6_ch_cserial",
                   "i126v7_me_cserial",
                   "i126v8_trxn_id",
                   "i126v9_stain",
                   "i126v10_cvv2",
                   "i126v13_pos_env",
                   "i130_term_capa",
                   "i131_tvr",
                   "i132_unpredict",
                   "i133_term_serial",
                   "i134_visa_discr",
                   "i135a_preauthtrace",
                   "i135b_purchtrace",
                   "i135c_crypttrace",
                   "i135d_keyversion",
                   "i136_cryptogram",
                   "i137_atc",
                   "i138_apl",
                   "i139_1_arpc",
                   "i139_2_arpc_rescd",
                   "i142_scriptsend",
                   "i143_script_res",
                   "i144_cryp_tr",
                   "i145_trm_cntry",
                   "i146_trm_date",
                   "i147_crypt_amt",
                   "i148_crypt_curr",
                   "i149_crypt_csbk"
              FROM "authorizations"@onldb02
             WHERE "eodserno" = v_eodserno;

         -- count number of rows inserted in the archive DB
         V_ROWS_INSERTED := SQL%ROWCOUNT;

         COMMIT;
         SELECT MAX(SERNO) INTO V_MAX_SERNO_AUTO FROM authorizations_test where eodserno = v_eodserno;
         SELECT MIN(SERNO) INTO V_MIN_SERNO_AUTO FROM authorizations_test where eodserno = v_eodserno;

         -- insert information about data transfer process into TCTDBS.LOADED_EODS table
         INSERT INTO LOADED_EODS_TEST (INSERT_DATE,
                                         MIN_SERNO,
                                         MAX_SERNO,
                                         ROWS_INSERTED,
                                         eodserno)
              VALUES (SYSDATE,
                      V_MIN_SERNO_AUTO,
                      V_MAX_SERNO_AUTO,
                      V_ROWS_INSERTED,
                      v_eodserno);

         DBMS_OUTPUT.put_line (V_ROWS_INSERTED || ' ROWS INSERTED');

         COMMIT;
   END IF;
EXCEPTION
   WHEN OTHERS
   THEN
      v_code := SQLCODE;
      v_errm := SQLERRM;

      INSERT INTO LOADED_EODS_TEST (INSERT_DATE,
                                      MIN_SERNO,
                                      MAX_SERNO,
                                      ROWS_INSERTED,
                                      INSERT_STATUS)
           VALUES (SYSDATE,
                   V_MIN_SERNO,
                   V_MAX_SERNO,
                   V_ROWS_INSERTED,
                   v_code || ' ' || v_errm);

      COMMIT;
END;
