CREATE TABLE MAX_CONCURRENT_JOBS (
    SAMPLE_DATE DATE,
    JOBS_RUNNING NUMBER);
    
    CREATE OR REPLACE PROCEDURE MAX_CONCURRENT_JOBS_MONITOR IS
BEGIN
     INSERT INTO MAX_CONCURRENT_JOBS
            SELECT SYSDATE, COUNT(*) FROM DBA_JOBS_RUNNING;
     COMMIT;
END;
/

DECLARE 
  v_jobno number;
BEGIN
DBMS_JOB.SUBMIT(
JOB => v_jobno,
WHAT => 'MAX_CONCURRENT_JOBS_MONITOR;',
NEXT_DATE => SYSDATE,
INTERVAL => 'SYSDATE + (5/1440)');
COMMIT;
END;
/

SELECT MAX(JOBS_RUNNING) FROM MAX_CONCURRENT_JOBS;

/*
SELECT JOB FROM DBA_JOBS WHERE WHAT='MAX_CONCURRENT_JOBS_MONITOR;';

EXEC DBMS_JOB.REMOVE(<JOB # from above>);

DROP PROCEDURE MAX_CONCURRENT_JOBS_MONITOR;

DROP TABLE MAX_CONCURRENT_JOBS;
*/