select * from ALL_SCHEDULER_JOB_LOG;

/* Formatted on 19.02.2014 14:28:39 (QP5 v5.227.12220.39754) */
SELECT status,LOG_DATE
  FROM ALL_SCHEDULER_JOB_LOG
 WHERE     job_name = 'IMPORT_AUTHORISATIONS'
       AND TRUNC (LOG_DATE) = TRUNC (SYSDATE);
       
SELECT status,LOG_DATE
  FROM ALL_SCHEDULER_JOB_LOG
 WHERE     job_name = 'DELETE_AUTHORISATIONS'
       AND TRUNC (LOG_DATE) = TRUNC (SYSDATE);
       
/* Formatted on 19.02.2014 15:07:07 (QP5 v5.227.12220.39754) */
SELECT COUNT (1)
  FROM ALL_SCHEDULER_JOB_LOG
 WHERE     job_name = 'IMPORT_AUTHORISATIONS'
       AND TRUNC (LOG_DATE) = TRUNC (SYSDATE)
       AND STATUS = 'SUCCEEDED';
       
SELECT COUNT (1)
  FROM ALL_SCHEDULER_JOB_LOG
 WHERE     job_name = 'DELETE_AUTHORISATIONS'
       AND TRUNC (LOG_DATE) = TRUNC (SYSDATE)
       AND STATUS = 'SUCCEEDED';