/* Formatted on 14.11.2014 12:37:13 (QP5 v5.227.12220.39754) */
SELECT    'CREATE USER '
       || USERNAME
       || ' IDENTIFIED BY VALUES '''
       || PASSWORD
       || ''''
       || ' DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE "'
       || PROFILE
       || '" ACCOUNT UNLOCK;'
  FROM dba_users
 WHERE USERNAME = :V_USERNAME;

;

SELECT 'GRANT ' || GRANTED_ROLE || ' TO ' || GRANTEE || ';'
  FROM DBA_ROLE_PRIVS
 WHERE GRANTEE = :V_USERNAME;

SELECT 'ALTER USER ' || USERNAME || ' DEFAULT ROLE ALL;'
  FROM dba_users
 WHERE USERNAME = :V_USERNAME;