CREATE TABLESPACE DWTMPETL_D_T DATAFILE 
  '+DWHS_DATA' SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE 30G,
  '+DWHS_DATA' SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE 30G,
  '+DWHS_DATA' SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE 30G,
  '+DWHS_DATA' SIZE 1G AUTOEXTEND ON NEXT 1G MAXSIZE 30G
LOGGING
DEFAULT 
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


SET TIMING ON ECHO ON TERMOUT ON SERVEROUTPUT ON TIMING ON FEEDBACK ON

DECLARE
    V_SQL          VARCHAR2 (1000);
    V_TABLESPACE   VARCHAR2 (20) DEFAULT 'DWTMPETL_D';
BEGIN
    DBMS_OUTPUT.ENABLE(1000000);

    FOR REC
        IN (  SELECT    'alter table '
                     || OWNER
                     || '.'
                     || TABLE_NAME
                     || ' move tablespace DWTMPETL_D_T  update indexes online'    AS SQL_CMD
                FROM DBA_TABLES
               WHERE TABLESPACE_NAME = V_TABLESPACE AND PARTITIONED = 'NO'
            ORDER BY OWNER, TABLE_NAME)
    LOOP
        V_SQL := REC.SQL_CMD;
        DBMS_OUTPUT.PUT_LINE (V_SQL);

      --  EXECUTE IMMEDIATE V_SQL;
    END LOOP;

    FOR REC_IND
        IN (  SELECT    'alter table '
                     || TABLE_OWNER
                     || '.'
                     || TABLE_NAME
                     || ' move partition '
                     || PARTITION_NAME
                     || ' tablespace DWTMPETL_D_T  update indexes online'    AS SQL_CMD
                FROM DBA_TAB_PARTITIONS
               WHERE     TABLESPACE_NAME = V_TABLESPACE
                     AND TABLE_NAME NOT LIKE 'BIN$%'
            ORDER BY TABLE_OWNER, TABLE_NAME, PARTITION_NAME)
    LOOP
        V_SQL := REC_IND.SQL_CMD;
        DBMS_OUTPUT.PUT_LINE (V_SQL);

      --  EXECUTE IMMEDIATE V_SQL;
    END LOOP;
END;

DROP TABLESPACE DWTMPETL_D INCLUDING CONTENTS AND DATAFILES;
ALTER TABLESPACE DWTMPETL_D_T RENAME TO DWTMPETL_D;

