-- трассировка определенной ошибки (например, для ORA-08103)
alter session set events '8103 trace name errorstack level 5';

-- после нахождение ошибки выключаем трассировку
alter session set events '8103 trace name context off';

-- находим партиции, в которых находятся ошибочные строки из полученного трейса (select value from v$diag_info where name = 'Default Trace File'):
-- в трейсе ищем по сочетанию: ORA-08103:

with badlist as (select * from table(sys.dbms_debug_vc2coll('AAC49xAAwAADJgQCxS', 'AAC49xAAwAADJgQEA2', 'AAC49xAAwAADJhSBly',
'AAC49xAAwAADJiAACc', 'AAC49xAAwAADJiAAKs', 'AAC49xAAwAADJiAAXV', 'AAC49xAAwAADJiAAXf', 'AAC49xAAwAADJiAAie', 'AAC49xAAwAADJiAAkf',
'AAC49xAAwAADJiAAy+', 'AAC49xAAwAADJiAAyu', 'AAC49xAAwAADJiAB/m', 'AAC49xAAwAADJiAB7C', 'AAC49xAAwAADJiABNF', 'AAC49xAAwAADJiABYw',
'AAC49xAAwAADJiABkD', 'AAC49xAAwAADJiABkH', 'AAC49xAAwAADJiAD4r', 'AAC49xAAwAADJiADmL', 'AAC49xAAwAADJiADmr', 'AAC49xAAwAADJiADuD',
'AAC49xAAwAADJihAmP', 'AAC49xAAwAADJihB96', 'AAC49xAAwAADJihBIr', 'AAC49xAAwAADJihBVI', 'AAC49xAAwAADJihBrU', 'AAC49xAAwAADJihC6y',
'AAC49xAAwAADJihDKk', 'AAC49xAAwAADJjDARD', 'AAC49xAAwAADJjDAzU', 'AAC49xAAwAADJjDBFK', 'AAC49xAAwAADJjDEAS', 'AAC49xAAwAADJjkAS3',
'AAC49xAAwAADJjkAUS', 'AAC49xAAwAADJjkB7y', 'AAC49xAAwAADJjkB8+', 'AAC49xAAwAADJjkBSB', 'AAC49xAAwAADJjkBh5', 'AAC49xAAwAADJoAA+U',
'AAC49xAAwAADJoAA+u', 'AAC49xAAwAADJoAA1E', 'AAC49xAAwAADJoAA4a', 'AAC49xAAwAADJoAA5Z', 'AAC49xAAwAADJoAA6t', 'AAC49xAAwAADJoAAAA',
'AAC49xAAwAADJoAAAB', 'AAC49xAAwAADJoAAAD', 'AAC49xAAwAADJoAAAF', 'AAC49xAAwAADJoAAAH', 'AAC49xAAwAADJoAAAJ', 'AAC49xAAwAADJoAAAL',
'AAC49xAAwAADJoAAAP', 'AAC49xAAwAADJoAAAX', 'AAC49xAAwAADJoAAAd', 'AAC49xAAwAADJoAAAf', 'AAC49xAAwAADJoAAB3', 'AAC49xAAwAADJoAABV',
'AAC49xAAwAADJoAABl', 'AAC49xAAwAADJoAABn', 'AAC49xAAwAADJoAAC1', 'AAC49xAAwAADJoAACL', 'AAC49xAAwAADJoAACh', 'AAC49xAAwAADJoAACj',
'AAC49xAAwAADJoAACr', 'AAC49xAAwAADJoAACt', 'AAC49xAAwAADJoAADt', 'AAC49xAAwAADJoAAE4', 'AAC49xAAwAADJoAAE8', 'AAC49xAAwAADJoAAEE',
'AAC49xAAwAADJoAAEI', 'AAC49xAAwAADJoAAEK', 'AAC49xAAwAADJoAAEM', 'AAC49xAAwAADJoAAEo', 'AAC49xAAwAADJoAAG3', 'AAC49xAAwAADJoAAG7',
'AAC49xAAwAADJoAAHp', 'AAC49xAAwAADJoAAJL', 'AAC49xAAwAADJoAAJb', 'AAC49xAAwAADJoAAJd', 'AAC49xAAwAADJoAAJf', 'AAC49xAAwAADJoAAKt',
'AAC49xAAwAADJoAALB', 'AAC49xAAwAADJoAALJ', 'AAC49xAAwAADJoAAMd', 'AAC49xAAwAADJoAAOZ', 'AAC49xAAwAADJoAAOl', 'AAC49xAAwAADJoAAPf',
'AAC49xAAwAADJoAAPh', 'AAC49xAAwAADJoAAQf', 'AAC49xAAwAADJoAAQt', 'AAC49xAAwAADJoAAQv', 'AAC49xAAwAADJoAARR', 'AAC49xAAwAADJoAARX',
'AAC49xAAwAADJoAARj', 'AAC49xAAwAADJoAATb', 'AAC49xAAwAADJoAATt', 'AAC49xAAwAADJoAAUF', 'AAC49xAAwAADJoAAVr', 'AAC49xAAwAADJoAAX3',
'AAC49xAAwAADJoAAXx', 'AAC49xAAwAADJoAAYV', 'AAC49xAAwAADJoAAZH', 'AAC49xAAwAADJoAAZd', 'AAC49xAAwAADJoAAah', 'AAC49xAAwAADJoAAbL',
'AAC49xAAwAADJoAAbV', 'AAC49xAAwAADJoAAbb', 'AAC49xAAwAADJoAAbd', 'AAC49xAAwAADJoAAdQ', 'AAC49xAAwAADJoAAfs', 'AAC49xAAwAADJoAAgA',
'AAC49xAAwAADJoAAiE', 'AAC49xAAwAADJoAAlT', 'AAC49xAAwAADJoAAmb', 'AAC49xAAwAADJoAAo9', 'AAC49xAAwAADJoAAob', 'AAC49xAAwAADJoAApZ',
'AAC49xAAwAADJoAAs/', 'AAC49xAAwAADJoAAs5', 'AAC49xAAwAADJoAAsj', 'AAC49xAAwAADJoAAtB', 'AAC49xAAwAADJoAAu1', 'AAC49xAAwAADJoAAu7',
'AAC49xAAwAADJoAAz0', 'AAC49xAAwAADJoAAzC', 'AAC49xAAwAADJoAAzY', 'AAC49xAAwAADJoAAzy', 'AAC49xAAwAADJoAB+s', 'AAC49xAAwAADJoAB1N',
'AAC49xAAwAADJoAB1Q', 'AAC49xAAwAADJoAB1U', 'AAC49xAAwAADJoAB2+', 'AAC49xAAwAADJoAB20', 'AAC49xAAwAADJoAB26', 'AAC49xAAwAADJoAB2G',
'AAC49xAAwAADJoAB2I', 'AAC49xAAwAADJoAB2S', 'AAC49xAAwAADJoAB2W', 'AAC49xAAwAADJoAB3E', 'AAC49xAAwAADJoAB3G', 'AAC49xAAwAADJoAB3K',
'AAC49xAAwAADJoAB3M', 'AAC49xAAwAADJoAB3s', 'AAC49xAAwAADJoAB5M', 'AAC49xAAwAADJoAB77', 'AAC49xAAwAADJoAB7P', 'AAC49xAAwAADJoAB7X',
'AAC49xAAwAADJoAB8V', 'AAC49xAAwAADJoAB8t', 'AAC49xAAwAADJoABNR', 'AAC49xAAwAADJoABNZ', 'AAC49xAAwAADJoABcI', 'AAC49xAAwAADJoABcK',
'AAC49xAAwAADJoABcO', 'AAC49xAAwAADJoABcS', 'AAC49xAAwAADJoABgE', 'AAC49xAAwAADJoABiv', 'AAC49xAAwAADJoABjb', 'AAC49xAAwAADJoABtO',
'AAC49xAAwAADJoAByH', 'AAC49xAAwAADJoACQw', 'AAC49xAAwAADJoACR2', 'AAC49xAAwAADJoACTC', 'AAC49xAAwAADJoACTu', 'AAC49xAAwAADJoACW+',
'AAC49xAAwAADJoACX+', 'AAC49xAAwAADJoACXE', 'AAC49xAAwAADJoACXy', 'AAC49xAAwAADJoACjJ', 'AAC49xAAwAADJoACm2', 'AAC49xAAwAADJoACu3',
'AAC49xAAwAADJoACvD', 'AAC49xAAwAADJoAD+j', 'AAC49xAAwAADJoADcc', 'AAC49xAAwAADJoADdt', 'AAC49xAAwAADJoADeQ', 'AAC49xAAwAADJoADew',
'AAC49xAAwAADJoADg0', 'AAC49xAAwAADJoADlo', 'AAC49xAAwAADJoADlq', 'AAC49xAAwAADJoADnI', 'AAC49xAAwAADJoADpH', 'AAC49xAAwAADJoADu3',
'AAC49xAAwAADJoADvs', 'AAC49xAAwAADJoADvw', 'AAC49xAAwAADJoADzF', 'AAC49xAAwAADJohA/0', 'AAC49xAAwAADJohABV', 'AAC49xAAwAADJohAK5',
'AAC49xAAwAADJohAku', 'AAC49xAAwAADJohAlO', 'AAC49xAAwAADJohApO', 'AAC49xAAwAADJohBAi', 'AAC49xAAwAADJohBBa', 'AAC49xAAwAADJohBBu',
'AAC49xAAwAADJohBDa', 'AAC49xAAwAADJohBHy', 'AAC49xAAwAADJohBLy', 'AAC49xAAwAADJohBM6', 'AAC49xAAwAADJohBXq', 'AAC49xAAwAADJohC1x',
'AAC49xAAwAADJohCz7', 'AAC49xAAwAADJohCzr', 'AAC49xAAwAADJohDAu', 'AAC49xAAwAADJohDPZ', 'AAC49xAAwAADJohDrh', 'AAC49xAAwAADJpCA/L',
'AAC49xAAwAADJpCAL/', 'AAC49xAAwAADJpCAMJ', 'AAC49xAAwAADJpCANd', 'AAC49xAAwAADJpCAOm', 'AAC49xAAwAADJpCAOq', 'AAC49xAAwAADJpCAXZ',
'AAC49xAAwAADJpCAYi', 'AAC49xAAwAADJpCB/x', 'AAC49xAAwAADJpCBzQ', 'AAC49xAAwAADJpCCHG', 'AAC49xAAwAADJpCCSe', 'AAC49xAAwAADJpCCeE',
'AAC49xAAwAADJpCCsK', 'AAC49xAAwAADJpCD60', 'AAC49xAAwAADJpCDDD', 'AAC49xAAwAADJpCDH7', 'AAC49xAAwAADJpCDck', 'AAC49xAAwAADJpjAAB',
'AAC49xAAwAADJpjAZk', 'AAC49xAAwAADJpjAfA', 'AAC49xAAwAADJpjBl3', 'AAC49xAAwAADJpjCBy', 'AAC49xAAwAADJpjCDe', 'AAC49xAAwAADJpjCDk',
'AAC49xAAwAADJpjCGX', 'AAC49xAAwAADJpjCNY', 'AAC49xAAwAADJpjCrZ', 'AAC49xAAwAADJqAAe6', 'AAC49xAAwAADJqAAnm', 'AAC49xAAwAADJqjBR2',
'AAC49xAAwAADJqjBRM', 'AAC49xAAwAADJqjC9K', 'AAC49xAAwAADJrEA5O', 'AAC49xAAwAADJrEA5U', 'AAC49xAAwAADJrEBGe', 'AAC49xAAxAADPAjCw5',
'AAC49xAAxAADPIABNl', 'AAC49xAAxAADPKAA7b', 'AAC49xAAxAADPKAAfQ', 'AAC49xAAxAADPKABjV', 'AAC49xAAxAADPKACHO', 'AAC49xAAxAADPKACI0',
'AAC49xAAxAADPKACIs', 'AAC49xAAxAADPKACKy', 'AAC49xAAxAADPKACR3', 'AAC49xAAxAADPKACTG', 'AAC49xAAxAADPKAD9c', 'AAC49xAAwAADJoAB1N',
'AAC49xAAwAADJoAB1Q', 'AAC49xAAwAADJoAB1U')))
select owner, segment_name, partition_name
from dba_extents, badlist where
file_id = dbms_rowid.rowid_relative_fno(column_value) and
dbms_rowid.rowid_block_number(column_value) between block_id and block_id + blocks - 1;
