SET DEFINE OFF;
Insert into SYSTEMUSERS
   (INSTITUTION_ID, INSTITUTIONSHORTCODE, SERNO, USERNAME, USERTYPE, 
    SCHEMANAME, LOGACTION)
 Values
   (0, 'CNTR', 21, 'PRO_ROLE', 'R', 
    'TCTDBS', 'Create');
COMMIT;
