/* Formatted on 25-11-2015 17:48:16 (QP5 v5.287) */
DECLARE
   my_task_name   VARCHAR2 (30);
   my_sqltext     CLOB;
BEGIN
   my_sqltext :=
      'SELECT TRADEDATE, FIRMNAME, FIRMID, TRDACCBID, SECURITYSNAME, SETTLEDATE, TRADENO, TRADETIMERES, BOARDID, BUYSELL, PRICE, TRADETYPE, QUANTITY, VAL, ORDERNO, CPFIRMID, EXHCOMM, ITSCOMM, CLRCOMM, COMMISSION, CLIENTCODE, SYS_DATE, SYS_TIME, SYS_TIMEMS 
from ( 
Select *
from ( 
SELECT BASE_T.TRADEDATE,
To_char(TO_TIMESTAMP(SUBSTR(To_Char(1000000+BASE_T.TRADETIME),2),''hh24miss''), ''hh24:mi:ss'') as TRADETIMERES ,
TRIM(TRAILING ''0'' FROM To_char(TO_TIMESTAMP(SUBSTR(To_Char(1000000+BASE_T.TRADETIME),2)||SUBSTR(To_Char(1000000+BASE_T.TRADEMICROSECONDS),2),''hh24missff''), ''hh24:mi:ss.ff'')) as TRADETIMEMSRES ,
BASE_T.FIRMID, FIRMS.INN as FIRMINN, FIRMS.NAME as FIRMNAME, FIRMS.LATNAME as FIRMLATNAME,
CLFirms.FIRMID as CLFIRMID, CLFirms.INN as CLFIRMINN, CLFirms.NAME as CLFIRMNAME, CLFirms.LATNAME as CLFIRMLATNAME, BANKACC.REALACCOUNT as EXTSETTLECODE,
SECS.SECURITYID, SECS.SHORTNAME as SECURITYSNAME, NVL(SECS.IsDerivative,INSTR.IsDerivative) as TradeDeriv, CURRENCY.CURRENCYID,CURRENCY.name as CURRENCYNAME,COCURRENCY.CURRENCYID as COCURRENCYID,COCURRENCY.name as COCURRENCYNAME,SECHIST.FACEVALUE, SECHIST.DECIMALS, 
BASE_T.SettleDate,BASE_T.TradeNo,BASE_T.BUYSELL,BASE_T.ORDERNO,
BASE_T.TYP as TradeType,BASE_T.price,BASE_T.QUANTITY,BASE_T.VAL,
BASE_T.CPFIRMID, CASE BASE_T.boardid When ''CETS'' Then '''' ELSE ''NCC0000100000'' End as CPFIRMIDCUX, 
CPFIRMS.INN as CPFIRMINN, CPFIRMS.NAME as CPFIRMNAME, CPFIRMS.LATNAME as CPFIRMLATNAME, BASE_T.PERIOD,
BASE_T.SettleCode,BASE_T.USERID,BASE_T.UserExchangeId,BASE_T.BrokerRef,BASE_T.ExtRef,BASE_T.EXHCOMM,
BASE_T.ITSCOMM,BASE_T.CLRCOMM,BASE_T.COMMISSION,
CLIENTCODES.CLIENTCODE,CLIENTCODES.TYP as CLIENTCODESTYP,CLIENTCODES.DETAILS,CLIENTCODES.SUBDETAILS,
BASE_T.PARENTTRADENO as RepoTradeNo,BOARDS.boardid, BOARDS.NAME as boardname, BOARDS.LATNAME as boardlatname,
BASE_T.AMOUNT, TRDACC.TYP as TRDACCTYP, TRDACC.BANKACCID as TRDACCBID,
CCLIENTCODES.CLIENTCODE as CLIENTCODEBenef,CLIENTCODES.TYP as CLIENTCODESTYPBenef,CCLIENTCODES.DETAILS as DETAILSBenef,CCLIENTCODES.SUBDETAILS as SUBDETAILSBenef,
PTRADES.SECURITYID as PSECURITYID, PTRADES.Shortname as PSECURITYSNAME,
BASE_T.ADDSESSION, 
REPLACE(REPLACE(BASE_T.ADDSESSION,''N'',''Основная сессия''),''Y'',''Дополнительная сессия'') as SessionName,
REPLACE(REPLACE(BASE_T.ADDSESSION,''N'',''Main Trading session''),''Y'',''Additional Trading session'') as SessionNameEN,
CASE BASE_T.TYP When ''S'' Then ''S''  When ''W'' Then ''S'' ELSE ''T'' End as TRADEGROUP,
BASE_T.TRADEDATE as SYS_DATE, BASE_T.TRADETIME as SYS_TIME, BASE_T.TRADEMICROSECONDS as SYS_TIMEMS,
TO_TIMESTAMP(To_char(BASE_T.TRADEDATE,''dd.mm.yyyy'')||SUBSTR(To_Char(1000000+BASE_T.TRADETIME),2)||SUBSTR(To_Char(1000000+BASE_T.TRADEMICROSECONDS),2),''dd.mm.yyyyhh24missff'') as filter_FullTime 
FROM 
INTERNALDM.V_CURR_TRADES BASE_T,
INTERNALDM.V_CURR_CLIENTCODES CLIENTCODES,
INTERNALDM.V_CURR_FIRMS FIRMS, 
INTERNALDM.V_CURR_TRDACC TRDACC, 
INTERNALDM.V_CURR_FIRMS CPFIRMS, 
INTERNALDM.V_CURR_BANKACC BANKACC,
INTERNALDM.V_CURR_FIRMS CLFirms,
INTERNALDM.V_CURR_BOARDS BOARDS,
INTERNALDM.V_CURR_SECS SECS,
INTERNALDM.V_CURR_CURRENCY CURRENCY,
INTERNALDM.V_CURR_CURRENCY COCURRENCY,
INTERNALDM.V_CURR_SECHIST SECHIST,
INTERNALDM.V_CURR_TRADES CTRADES,
INTERNALDM.V_CURR_CLIENTCODES CCLIENTCODES,
INTERNALDM.V_CURR_INSTR INSTR,
(SELECT SECS.SECURITYID, SECS.Shortname, BASE_T.TRADENO,BASE_T.BUYSELL 
    FROM INTERNALDM.V_CURR_TRADES BASE_T,INTERNALDM.V_CURR_SECS SECS 
    WHERE  BASE_T.SECURITYID  = SECS.SECURITYID
    and TRADEDATE between to_date(''2014-11-25'',''yyyy-mm-dd'') and to_date(''2015-11-25'',''yyyy-mm-dd'') ) PTRADES 
WHERE BASE_T.FIRMID = FIRMS.FIRMID AND BASE_T.FIRMID = TRDACC.FIRMID AND BASE_T.TRDACCID = TRDACC.TRDACCID AND CPFIRMS.FIRMID = BASE_T.CPFIRMID AND BANKACC.BANKACCID = TRDACC.BANKACCID AND BASE_T.TRADENO = CTRADES.TRADENO 
AND BASE_T.BUYSELL != CTRADES.BUYSELL AND BASE_T.TRADEDATE = CTRADES.TRADEDATE and BASE_T.CLEARINGFIRMID =  CLFirms.firmid and BASE_T.securityid = SECS.securityid and BASE_T.boardid = BOARDS.boardid
and SECS.FACEUNIT = CURRENCY.CURRENCYID and SECS.CURRENCYID = COCURRENCY.CURRENCYID and SECHIST.BoardID = ''CETS'' and SECHIST.TRADEDATE  = BASE_T.TRADEDATE  and SECHIST.SECURITYID = BASE_T.SECURITYID
and BASE_T.CLIENTCODEID = CLIENTCODES.CLIENTCODEID(+) and CTRADES.CLIENTCODEID = CCLIENTCODES.CLIENTCODEID(+) and PTRADES.TRADENO(+) = BASE_T.PARENTTRADENO and (PTRADES.BUYSELL != BASE_T.BUYSELL or PTRADES.BUYSELL is null) 
and SECS.INSTRID = INSTR.INSTRID 
and BASE_T.TRADEDATE between to_date(''2014-11-25'',''yyyy-mm-dd'') and to_date(''2015-11-25'',''yyyy-mm-dd'')
and INSTR.TYP not in (''I'', ''W'') 
and BASE_T.SettleDate between to_date(''2015-11-30'',''yyyy-mm-dd'') and to_date(''2016-12-28'',''yyyy-mm-dd'')
and BASE_T.FIRMID in (:bnd1) 
and CURRENCY.ID in (:bnd2) 
and COCURRENCY.ID in (:bnd3) 
 ) T 
Where 1=1  
Order by TradeNo 
) T
'   ;

   my_task_name :=
      DBMS_SQLTUNE.CREATE_TUNING_TASK (
         sql_text      => my_sqltext,
         bind_list     => sql_binds (anydata.ConvertVarchar2 ('MB0089500000'),
                                     anydata.ConvertNumber (2777),
                                     anydata.ConvertNumber (2773)),
         user_name     => 'ARDB_USER',
         scope         => 'COMPREHENSIVE',
         time_limit    => 1800,
         task_name     => 'sql_tuning_task_20151125_7',
         description   => 'Task to tune a query on INTERNALDM.V_CURR%');
END;
/

BEGIN
   DBMS_SQLTUNE.EXECUTE_TUNING_TASK (
      task_name   => 'sql_tuning_task_20151125_7');
END;
/

SELECT task_name, status
  FROM dba_advisor_log
 WHERE owner = 'ARDB_USER';

SELECT DBMS_SQLTUNE.report_tuning_task ('sql_tuning_task_20151125_7')
          AS recommendations
  FROM DUAL;