SPOOL 01_primary_to_standby.log
ALTER SYSTEM ARCHIVE LOG CURRENT;
ALTER DATABASE COMMIT TO SWITCHOVER TO PHYSICAL STANDBY WITH SESSION SHUTDOWN;
SHUTDOWN IMMEDIATE;
connect sys/trjvthc@ULTRALB as sysdba;
STARTUP NOMOUNT;
ALTER DATABASE MOUNT STANDBY DATABASE;
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;
SPOOL OFF
EXIT;