SPOOL 03_back_to_primary.log
ALTER SYSTEM ARCHIVE LOG CURRENT;
ALTER DATABASE COMMIT TO SWITCHOVER TO PHYSICAL STANDBY WITH SESSION SHUTDOWN;
SHUTDOWN IMMEDIATE;
connect sys/trjvthc@ULTRASTN as sysdba;
STARTUP NOMOUNT;
ALTER DATABASE MOUNT STANDBY DATABASE;
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;
SPOOL OFF
EXIT;