-- FLASHBACK DATABASE

SELECT OLDEST_FLASHBACK_TIME,
       ROUND (FLASHBACK_SIZE / 1024 / 1024 / 1024, 1) FLASHBACK_SIZE_GB,
       ROUND (ESTIMATED_FLASHBACK_SIZE / 1024 / 1024 / 1024, 1)
           ESTIMATED_FLASHBACK_SIZE_GB,
       RETENTION_TARGET
  FROM V$FLASHBACK_DATABASE_LOG;
SELECT * FROM V$FLASHBACK_DATABASE_LOGFILE;
SELECT * FROM V$FLASHBACK_DATABASE_STAT;
SELECT * FROM V$FLASH_RECOVERY_AREA_USAGE;

-- result cashe (MUST BE ENABLED) !!!

EXEC DBMS_RESULT_CACHE.memory_report(detailed => true);

--

select Trade_date,v1.due_date,board_id,settle_code_id,
Buy_sell, v3.typ,security_id,currency_code,
sum(Amount)/10 as volume
from cbsysuser.v_eq_trades v1
left join cbsysuser.v_eq_currency v2 on v1.currency_id=v2.currency_id
left join cbsysuser.v_eq_clientcodes v3 on v1.client_code_id=v3.client_code_id
where v1.St_Actual='A'
and Confirmed='C'
and v1.typ in ('T','N','P')
and v1.status='M'
and v1.currency_id in (select currency_id from cbsysuser.v_eq_currency where currency_code in ('SUR','EUR','USD'))
and trade_date between add_months(sysdate,-12)-17 and add_months(sysdate,-12)-2
and security_id not like '%EUR%'
and v1.client_code_id is not null
group by Trade_date,v1.due_date,board_id,settle_code_id,Buy_sell,v3.typ,security_id,currency_code
order by Trade_date,v1.due_date,board_id,settle_code_id,Buy_sell,typ,security_id,currency_code;

-- problems with blocking sessions at 01-45 - 02-00 (sql in sessions which blocks another session):
-- made indexes in CBMIRROR.CURR_ORDERS_BASE and CBMIRROR.ORDERS_BASE invisible !!! at 25.01.2017

MERGE INTO CBMIRROR.CURR_ORDERS_BASE A
     USING (SELECT "TRANSACTIONS",
                   "ORDERNO",
                   "ENTRYDATE",
                   "ENTRYTIME",
                   "ACTIVATIONDATE",
                   "ACTIVATIONTIME",
                   "SECURITYID",
                   "BOARDID",
                   "USERID",
                   "FIRMID",
                   "TRDACCID",
                   "BUYSELL",
                   "TYP",
                   "STATUS",
                   "PRICE",
                   "QUANTITY",
                   "QTYHIDDEN",
                   "BALANCE",
                   "EXPIRYDATE",
                   "AMENDDATE",
                   "AMENDTIME",
                   "LINKEDORDER",
                   "CUSTODIANID",
                   "COUNTERPARTYID",
                   "CPFIRMID",
                   "BROKERREF",
                   "MATCHREF",
                   "EXCHANGEID",
                   "PERIOD",
                   "ISMARKETMAKER",
                   "SESSIONNO",
                   "VAL",
                   "ACCINT",
                   "YIELD",
                   "REPORATE",
                   "PRICE2",
                   "VAL2",
                   "REFUNDRATE",
                   "LINKEDQUOTE",
                   "SETTLECODE",
                   "USAGECASH",
                   "EXTREF",
                   "USEREXCHANGEID",
                   "CLIENTCODEID",
                   "GATEWAYID",
                   "AUCTNO",
                   "INSERTDATE",
                   "UPDATEDATE",
                   "SETTLEDATE",
                   "ENTRYMICROSECONDS",
                   "AMENDMICROSECONDS",
                   "ORIGINVALUE",
                   "BASEPRICE",
                   "SYSTEMREF",
                   "BANKID",
                   "BANKACCID",
                   "ISSTABILISER",
                   "SETTLEDATE1",
                   "TRANSACTIONNO",
                   "ASP"
              FROM CURR.ORDERS_BASE@DWH_EQ
             WHERE     ENTRYDATE = TO_DATE ('20012017', 'DDMMYYYY')
                   AND ORDERNO BETWEEN 16607386530 AND 16609843837
            MINUS
            SELECT "TRANSACTIONS",
                   "ORDERNO",
                   "ENTRYDATE",
                   "ENTRYTIME",
                   "ACTIVATIONDATE",
                   "ACTIVATIONTIME",
                   "SECURITYID",
                   "BOARDID",
                   "USERID",
                   "FIRMID",
                   "TRDACCID",
                   "BUYSELL",
                   "TYP",
                   "STATUS",
                   "PRICE",
                   "QUANTITY",
                   "QTYHIDDEN",
                   "BALANCE",
                   "EXPIRYDATE",
                   "AMENDDATE",
                   "AMENDTIME",
                   "LINKEDORDER",
                   "CUSTODIANID",
                   "COUNTERPARTYID",
                   "CPFIRMID",
                   "BROKERREF",
                   "MATCHREF",
                   "EXCHANGEID",
                   "PERIOD",
                   "ISMARKETMAKER",
                   "SESSIONNO",
                   "VAL",
                   "ACCINT",
                   "YIELD",
                   "REPORATE",
                   "PRICE2",
                   "VAL2",
                   "REFUNDRATE",
                   "LINKEDQUOTE",
                   "SETTLECODE",
                   "USAGECASH",
                   "EXTREF",
                   "USEREXCHANGEID",
                   "CLIENTCODEID",
                   "GATEWAYID",
                   "AUCTNO",
                   "INSERTDATE",
                   "UPDATEDATE",
                   "SETTLEDATE",
                   "ENTRYMICROSECONDS",
                   "AMENDMICROSECONDS",
                   "ORIGINVALUE",
                   "BASEPRICE",
                   "SYSTEMREF",
                   "BANKID",
                   "BANKACCID",
                   "ISSTABILISER",
                   "SETTLEDATE1",
                   "TRANSACTIONNO",
                   "ASP"
              FROM CBMIRROR.CURR_ORDERS_BASE
             WHERE     ENTRYDATE = TO_DATE ('20012017', 'DDMMYYYY')
                   AND ORDERNO BETWEEN 16607386530 AND 16609843837) B
        ON (    A."ENTRYDATE" = B."ENTRYDATE"
            AND A."ENTRYDATE" = TO_DATE ('20012017', 'DDMMYYYY')
            AND A."ORDERNO" = B."ORDERNO")
WHEN MATCHED
THEN
    UPDATE SET A."TRANSACTIONS" = B."TRANSACTIONS",
               A."ENTRYTIME" = B."ENTRYTIME",
               A."ACTIVATIONDATE" = B."ACTIVATIONDATE",
               A."ACTIVATIONTIME" = B."ACTIVATIONTIME",
               A."SECURITYID" = B."SECURITYID",
               A."BOARDID" = B."BOARDID",
               A."USERID" = B."USERID",
               A."FIRMID" = B."FIRMID",
               A."TRDACCID" = B."TRDACCID",
               A."BUYSELL" = B."BUYSELL",
               A."TYP" = B."TYP",
               A."STATUS" = B."STATUS",
               A."PRICE" = B."PRICE",
               A."QUANTITY" = B."QUANTITY",
               A."QTYHIDDEN" = B."QTYHIDDEN",
               A."BALANCE" = B."BALANCE",
               A."EXPIRYDATE" = B."EXPIRYDATE",
               A."AMENDDATE" = B."AMENDDATE",
               A."AMENDTIME" = B."AMENDTIME",
               A."LINKEDORDER" = B."LINKEDORDER",
               A."CUSTODIANID" = B."CUSTODIANID",
               A."COUNTERPARTYID" = B."COUNTERPARTYID",
               A."CPFIRMID" = B."CPFIRMID",
               A."BROKERREF" = B."BROKERREF",
               A."MATCHREF" = B."MATCHREF",
               A."EXCHANGEID" = B."EXCHANGEID",
               A."PERIOD" = B."PERIOD",
               A."ISMARKETMAKER" = B."ISMARKETMAKER",
               A."SESSIONNO" = B."SESSIONNO",
               A."VAL" = B."VAL",
               A."ACCINT" = B."ACCINT",
               A."YIELD" = B."YIELD",
               A."REPORATE" = B."REPORATE",
               A."PRICE2" = B."PRICE2",
               A."VAL2" = B."VAL2",
               A."REFUNDRATE" = B."REFUNDRATE",
               A."LINKEDQUOTE" = B."LINKEDQUOTE",
               A."SETTLECODE" = B."SETTLECODE",
               A."USAGECASH" = B."USAGECASH",
               A."EXTREF" = B."EXTREF",
               A."USEREXCHANGEID" = B."USEREXCHANGEID",
               A."CLIENTCODEID" = B."CLIENTCODEID",
               A."GATEWAYID" = B."GATEWAYID",
               A."AUCTNO" = B."AUCTNO",
               A."INSERTDATE" = B."INSERTDATE",
               A."UPDATEDATE" = B."UPDATEDATE",
               A."SETTLEDATE" = B."SETTLEDATE",
               A."ENTRYMICROSECONDS" = B."ENTRYMICROSECONDS",
               A."AMENDMICROSECONDS" = B."AMENDMICROSECONDS",
               A."ORIGINVALUE" = B."ORIGINVALUE",
               A."BASEPRICE" = B."BASEPRICE",
               A."SYSTEMREF" = B."SYSTEMREF",
               A."BANKID" = B."BANKID",
               A."BANKACCID" = B."BANKACCID",
               A."ISSTABILISER" = B."ISSTABILISER",
               A."SETTLEDATE1" = B."SETTLEDATE1",
               A."TRANSACTIONNO" = B."TRANSACTIONNO",
               A."ASP" = B."ASP"
WHEN NOT MATCHED
THEN
    INSERT     (A."TRANSACTIONS",
                A."ORDERNO",
                A."ENTRYDATE",
                A."ENTRYTIME",
                A."ACTIVATIONDATE",
                A."ACTIVATIONTIME",
                A."SECURITYID",
                A."BOARDID",
                A."USERID",
                A."FIRMID",
                A."TRDACCID",
                A."BUYSELL",
                A."TYP",
                A."STATUS",
                A."PRICE",
                A."QUANTITY",
                A."QTYHIDDEN",
                A."BALANCE",
                A."EXPIRYDATE",
                A."AMENDDATE",
                A."AMENDTIME",
                A."LINKEDORDER",
                A."CUSTODIANID",
                A."COUNTERPARTYID",
                A."CPFIRMID",
                A."BROKERREF",
                A."MATCHREF",
                A."EXCHANGEID",
                A."PERIOD",
                A."ISMARKETMAKER",
                A."SESSIONNO",
                A."VAL",
                A."ACCINT",
                A."YIELD",
                A."REPORATE",
                A."PRICE2",
                A."VAL2",
                A."REFUNDRATE",
                A."LINKEDQUOTE",
                A."SETTLECODE",
                A."USAGECASH",
                A."EXTREF",
                A."USEREXCHANGEID",
                A."CLIENTCODEID",
                A."GATEWAYID",
                A."AUCTNO",
                A."INSERTDATE",
                A."UPDATEDATE",
                A."SETTLEDATE",
                A."ENTRYMICROSECONDS",
                A."AMENDMICROSECONDS",
                A."ORIGINVALUE",
                A."BASEPRICE",
                A."SYSTEMREF",
                A."BANKID",
                A."BANKACCID",
                A."ISSTABILISER",
                A."SETTLEDATE1",
                A."TRANSACTIONNO",
                A."ASP")
        VALUES (B."TRANSACTIONS",
                B."ORDERNO",
                B."ENTRYDATE",
                B."ENTRYTIME",
                B."ACTIVATIONDATE",
                B."ACTIVATIONTIME",
                B."SECURITYID",
                B."BOARDID",
                B."USERID",
                B."FIRMID",
                B."TRDACCID",
                B."BUYSELL",
                B."TYP",
                B."STATUS",
                B."PRICE",
                B."QUANTITY",
                B."QTYHIDDEN",
                B."BALANCE",
                B."EXPIRYDATE",
                B."AMENDDATE",
                B."AMENDTIME",
                B."LINKEDORDER",
                B."CUSTODIANID",
                B."COUNTERPARTYID",
                B."CPFIRMID",
                B."BROKERREF",
                B."MATCHREF",
                B."EXCHANGEID",
                B."PERIOD",
                B."ISMARKETMAKER",
                B."SESSIONNO",
                B."VAL",
                B."ACCINT",
                B."YIELD",
                B."REPORATE",
                B."PRICE2",
                B."VAL2",
                B."REFUNDRATE",
                B."LINKEDQUOTE",
                B."SETTLECODE",
                B."USAGECASH",
                B."EXTREF",
                B."USEREXCHANGEID",
                B."CLIENTCODEID",
                B."GATEWAYID",
                B."AUCTNO",
                B."INSERTDATE",
                B."UPDATEDATE",
                B."SETTLEDATE",
                B."ENTRYMICROSECONDS",
                B."AMENDMICROSECONDS",
                B."ORIGINVALUE",
                B."BASEPRICE",
                B."SYSTEMREF",
                B."BANKID",
                B."BANKACCID",
                B."ISSTABILISER",
                B."SETTLEDATE1",
                B."TRANSACTIONNO",
                B."ASP");