CREATE USER "SCHEMA_READ_ONLY" PROFILE "MONITORING_PROFILE" IDENTIFIED BY "router" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP1" QUOTA 50 M ON "USERS" ACCOUNT UNLOCK
GRANT CREATE SESSION TO "SCHEMA_READ_ONLY"
GRANT SELECT ANY TABLE TO "SCHEMA_READ_ONLY"
GRANT "CONNECT" TO "SCHEMA_READ_ONLY"
