see:
How To Move The DB Audit Trails To A New Tablespace Using DBMS_AUDIT_MGMT? (Doc ID 1328239.1)
Known Issues When Using: DBMS_AUDIT_MGMT (Doc ID 804624.1)

--

  SELECT TABLE_NAME, TABLESPACE_NAME
    FROM DBA_TABLES
   WHERE TABLE_NAME IN ('AUD$', 'FGA_LOG$')
ORDER BY TABLE_NAME;

SELECT SEGMENT_NAME, BYTES / 1024 / 1024 SIZE_IN_MEGABYTES
  FROM DBA_SEGMENTS
 WHERE SEGMENT_NAME IN ('AUD$', 'FGA_LOG$');

SELECT T.TABLE_NAME, TS.SEGMENT_SPACE_MANAGEMENT
  FROM DBA_TABLES T, DBA_TABLESPACES TS
 WHERE     TS.TABLESPACE_NAME = T.TABLESPACE_NAME
       AND T.TABLE_NAME IN ('AUD$', 'FGA_LOG$');

BEGIN
   DBMS_AUDIT_MGMT.SET_AUDIT_TRAIL_LOCATION (
      AUDIT_TRAIL_TYPE             => DBMS_AUDIT_MGMT.AUDIT_TRAIL_AUD_STD, --this moves table AUD$
      AUDIT_TRAIL_LOCATION_VALUE   => 'AUDIT_TBS');
END;

BEGIN
   DBMS_AUDIT_MGMT.SET_AUDIT_TRAIL_LOCATION (
      AUDIT_TRAIL_TYPE             => DBMS_AUDIT_MGMT.AUDIT_TRAIL_FGA_STD, --this moves table FGA_LOG$
      AUDIT_TRAIL_LOCATION_VALUE   => 'AUDIT_TBS');
END;

  SELECT TABLE_NAME, TABLESPACE_NAME
    FROM DBA_TABLES
   WHERE TABLE_NAME IN ('AUD$', 'FGA_LOG$')
ORDER BY TABLE_NAME;

SELECT OWNER,
       TABLE_NAME,
       SEGMENT_NAME,
       TABLESPACE_NAME
  FROM DBA_LOBS
 WHERE TABLE_NAME in ('FGA_LOG$','AUD$');

SELECT OWNER,
       TABLE_NAME,
       INDEX_NAME,
       INDEX_TYPE,
       TABLESPACE_NAME
  FROM DBA_INDEXES
 WHERE TABLE_NAME in ('FGA_LOG$','AUD$');