{
 "title": "Mongo bd dash",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values({exporter=\"mongodb\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DB - Documents and connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations",
     "type": "timeseries",
     "description": "количество операций MongoDB, выполненных на этом сервере, по типу. command - Количество команд (aggregate, create, drop и т.д.) («в среднем за минуту» (скорость роста))",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (state)(rate(mongodb_mongod_metrics_document_total{job=\"$job\", instance=~\"$instance:9216\"}[1m]))",
       "legendFormat": "state: {{state}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "description": "количество соединений с БД со статусами («в среднем за минуту» (скорость роста))",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (state)(rate(mongodb_connections{job=\"$job\", instance=~\"$instance:9216\"}[1m]))",
       "legendFormat": "state: {{state}}"
      }
     ]
    },
    {
     "title": "Operations",
     "type": "timeseries",
     "description": "количество операций MongoDB, выполненных на этом сервере, по типу. command - Количество команд (aggregate, create, drop и т.д.) («в среднем за минуту» (скорость роста))",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (legacy_op_type) (\n  rate(mongodb_ss_opcounters{job=\"$job\", instance=~\"$instance:9216\"}[1m])\n)",
       "legendFormat": "state: {{legacy_op_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB - user collection useful stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Средняя задержка READ операций на коллекции (микросекунд на операцию)",
     "type": "timeseries",
     "description": "показывает среднюю задержку операций на коллекции, помогает выявлять медленные операции.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum by (database,collection) (rate(mongodb_collstats_latencyStats_reads_latency{job=\"$job\", instance=~\"$instance:9216\"}[1m])) / sum by (database,collection) (rate(mongodb_collstats_latencyStats_reads_ops{job=\"$job\", instance=~\"$instance:9216\"}[1m]))",
       "legendFormat": "{{database}} / {{collection}}"
      }
     ]
    },
    {
     "title": "Средняя задержка COMMAND операций на коллекции (микросекунд на команду)",
     "type": "timeseries",
     "description": "показывает среднюю задержку операций на коллекции, помогает выявлять медленные операции (secondary members).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "sum by (database,collection) (rate(mongodb_collstats_latencyStats_commands_latency{job=\"$job\", instance=~\"$instance:9216\"}[1m])) / sum by (database,collection) (rate(mongodb_collstats_latencyStats_commands_ops{job=\"$job\", instance=~\"$instance:9216\"}[1m]))",
       "legendFormat": "{{database}} / {{collection}}"
      }
     ]
    },
    {
     "title": "Неиспользуемые индексы",
     "type": "timeseries",
     "description": "Индексы с нулевым количеством обращений, исключая служебные",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "sum by (database,collection,key_name) (\n  mongodb_indexstats_accesses_ops{job=\"$job\", instance=~\"$instance:9216\", key_name!=\"_id_\"} == 0\n)",
       "legendFormat": "{{database}} / {{collection}} {{key_name}}"
      }
     ]
    },
    {
     "title": "Процент размера индексов для коллекции (до 100%)",
     "type": "timeseries",
     "description": "Рост коллекции и индексной памяти, контроль использования хранилища",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "sum by (database,collection) (mongodb_collstats_storageStats_totalIndexSize{job=\"$job\", instance=~\"$instance:9216\"})\n/\nsum by (database,collection) (mongodb_collstats_storageStats_totalSize{job=\"$job\", instance=~\"$instance:9216\"}) * 100",
       "legendFormat": "{{database}} / {{collection}}"
      }
     ]
    }
   ]
  },
  { "title": "DB - sizes and objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Sizes of DB, Gb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "(sum by (database)(mongodb_mongod_db_data_size_bytes{job=\"$job\", instance=~\"$instance:9216\"}))/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG object size in a DB",
   "type": "timeseries",
   "description": "если avgObjSize резко увеличивается, значит в коллекциях появляются большие документы.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_dbstats_avgObjSize{job=\"$job\", instance=~\"$instance:9216\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sizes of DB, Mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(sum by (database)(mongodb_mongod_db_data_size_bytes{job=\"$job\", instance=~\"$instance:9216\"})) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of indexes in a DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_mongod_db_indexes_total{job=\"$job\", instance=~\"$instance:9216\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of all collections in a DB, Gb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_mongod_db_data_size_bytes{job=\"$job\", instance=~\"$instance:9216\"})/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of collections in a DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (database)(mongodb_dbstats_collections{job=\"$job\", instance=~\"$instance:9216\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Size of collections in a DB, Gb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(sum by (database, collection) (\n  mongodb_collstats_storageStats_size{job=\"$job\", instance=~\"$instance:9216\"}\n) / 1024 / 1024 / 1024)",
     "legendFormat": "{{database}} / {{collection}}"
    }
   ]
  },
  { "title": "DB - Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Replicaset member health",
   "type": "stat",
   "description": "1 = OK, 0 - NOT ok",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (member_idx, member_state) (mongodb_rs_members_health{job=\"$job\", instance=~\"$instance:9216\"})",
     "legendFormat": "{{member_idx}} {{ member_state}}"
    }
   ]
  },
  {
   "title": "Compatibility Version",
   "type": "stat",
   "description": "FCV version",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_featureCompatibilityVersion_major{job=\"$job\", instance=~\"$instance:9216\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "timeseries",
   "description": "лаг репликации с primary сервером",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_member_replication_lag{job=\"$job\", instance=~\"$instance:9216\"}",
     "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
    }
   ]
  },
  {
   "title": "oplog timestamp diff (seconds)",
   "type": "timeseries",
   "description": "разница между началом и концом oplog",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(mongodb_mongod_replset_oplog_head_timestamp{job=\"$job\", instance=~\"$instance:9216\"} - mongodb_mongod_replset_oplog_tail_timestamp{job=\"$job\", instance=~\"$instance:9216\"})",
     "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
    }
   ]
  },
  {
   "title": "OpLog size",
   "type": "timeseries",
   "description": " размер OpLog на диске",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_oplog_stats_storageStats_size{job=\"$job\", instance=~\"$instance:9216\"}",
     "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
    }
   ]
  },
  {
   "title": "DB - Размеры данных и индексов (примеры)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "collection oplog.rs.stats total size",
     "type": "timeseries",
     "description": "Размер данных коллекции. Мониторинг роста данных важен для планирования ресурсов.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "mongodb_oplog_stats_storageStats_size{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    },
    {
     "title": "collection config.transactions.stats.storageStats total index size",
     "type": "timeseries",
     "description": "Фактический размер хранилища, занимаемый коллекцией.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "mongodb_config_transactions_stats_storageStats_totalIndexSize{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB - connections efffectivity % (calculated)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "Качество подключений/доступности узла MongoDB глазами клиентов и реплик (%).",
   "type": "timeseries",
   "description": "0–1% — норма (могут быть редкие сетевые глюки, закрытые сокеты).\n\nВыше 5–10% — уже сигнал проблемы (драйверы массово не могут корректно подключиться или происходят ошибки в кластере).\n\nОчень высокий процент (20–100%) — обычно говорит о том, что узел перегружен, не принимает новые соединения, либо есть серьёзные сетевые/конфигурационные ошибки.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "(increase(mongodb_ss_metrics_commands_hello_failed{job=\"$job\", instance=~\"$instance:9216\"}[1m]) / increase(mongodb_ss_metrics_commands_hello_total{job=\"$job\", instance=~\"$instance:9216\"}[1m]))*100",
     "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
    },
    {
     "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
    }
   ]
  },
  {
   "title": "показатель эффективности использования speculative authentication (%)",
   "type": "timeseries",
   "description": "Значение близко к 100% → почти все speculative попытки завершаются неудачно. Это нормально, если клиенты не используют эту возможность (обычно драйверы делают так: пробуют, но большинство серверов/настроек не поддерживают).\n\nЗначение низкое (например, <20–30%) → значительная часть speculative-аутентификаций успешна (обычно при правильно настроенных драйверах и актуальных версиях MongoDB).\n\nРезкий рост процента ошибок может говорить о том, что:\n\nклиенты пробуют не тем методом или с неверными параметрами;\nизменена конфигурация безопасности;\nдрайверы устарели и не умеют правильно согласовывать механизм.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "(increase(mongodb_ss_security_authentication_mechanisms_SCRAM_SHA_256_speculativeAuthenticate_successful {job=\"$job\", instance=~\"$instance:9216\"}[1m]) / increase (mongodb_ss_security_authentication_mechanisms_SCRAM_SHA_256_speculativeAuthenticate_received {job=\"$job\", instance=~\"$instance:9216\"}[1m]))*100",
     "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
    }
   ]
  },
  {
   "title": "качество работы с курсорами (%) уср. за полчаса",
   "type": "timeseries",
   "description": "0–1% — норма (редкие «cursor not found» естественны).\n\n>5% — повод проверить работу приложений (часто слишком медленно обрабатывают данные).\n\n>10–20% — системная проблема (истечение курсоров из-за короткого cursorTimeout, перегрузка БД или неверный код клиента).",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "expr": "(increase(mongodb_ss_metrics_commands_getMore_failed{job=\"$job\", instance=~\"$instance:9216\"}[30m]) / (increase(mongodb_ss_metrics_commands_getMore_total{job=\"$job\", instance=~\"$instance:9216\"}[30m])))*100",
     "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
    }
   ]
  },
  {
   "title": "OS - Обзор системы (Overview)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "node load1",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 281 },
     "targets": [
      {
       "expr": "node_load1{instance=~\"$instance:9100\"}",
       "legendFormat": "{{ __name__ }} {{ instance }}"
      }
     ]
    },
    {
     "title": "node load5",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 281 },
     "targets": [
      {
       "expr": "node_load5{instance=~\"$instance:9100\"}",
       "legendFormat": "{{ __name__ }} {{ instance }}"
      }
     ]
    },
    {
     "title": "node load15",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 10, "y": 281 },
     "targets": [
      {
       "expr": "node_load15{instance=~\"$instance:9100\"}",
       "legendFormat": "{{ __name__ }} {{ instance }}"
      }
     ]
    },
    {
     "title": "node network up",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 15, "y": 281 },
     "targets": [
      {
       "expr": "node_network_up{device=\"bond0\", instance=~\"$instance:9100\"}",
       "legendFormat": "{{ __name__ }} {{ instance }}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 281 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{instance=~\"$instance:9100\"} - node_boot_time_seconds{instance=~\"$instance:9100\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OS - HW resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$instance:9100\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance:9100\"}) by (cpu)))",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$instance:9100\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance:9100\"}) by (cpu)))",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$instance:9100\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance:9100\"}) by (cpu)))",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$instance:9100\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance:9100\"}) by (cpu)))",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$instance:9100\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance:9100\"}) by (cpu)))",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$instance:9100\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=~\"$instance:9100\"}) by (cpu)))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "CPU capacity planning",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 7, "y": 288 },
     "targets": [
      {
       "expr": "rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$instance:9100\"}[24h])",
       "legendFormat": "Node: {{ instance }}, CPU {{ cpu }}  trend"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:9100\"}",
       "legendFormat": "{{instance}} RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:9100\"} - node_memory_MemFree_bytes{instance=~\"$instance:9100\"} - (node_memory_Cached_bytes{instance=~\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=~\"$instance:9100\"} + node_memory_SReclaimable_bytes{instance=~\"$instance:9100\"})",
       "legendFormat": "{{instance}} RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$instance:9100\"} + node_memory_Buffers_bytes{instance=~\"$instance:9100\"} + node_memory_SReclaimable_bytes{instance=~\"$instance:9100\"}",
       "legendFormat": "{{instance}} RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$instance:9100\"}",
       "legendFormat": "{{instance}} RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\"} - node_memory_SwapFree_bytes{instance=~\"$node\"})",
       "legendFormat": "{{instance}} SWAP Used"
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 294 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance:9100\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"$instance:9100\",device!~'rootfs'})",
       "legendFormat": "{{ instance }}: {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 294 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance:9100\", device=~\"eth0|aggi|int.*\"}[$__rate_interval])*8",
       "legendFormat": "{{instance}} recv {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance:9100\", device=~\"eth0|aggi|int.*\"}[$__rate_interval])*8",
       "legendFormat": "{{instance}} trans {{device}} "
      }
     ]
    }
   ]
  },
  {
   "title": "DB - WiredTiger (internal use)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "cache bytes dirty in the cache cumulative",
     "type": "timeseries",
     "description": "Текущий общий размер грязных данных в кэше oplog.rs.stats. Рост скачками может судить о проблемах с произв. записи («в среднем за минуту» (скорость роста))",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(mongodb_oplog_stats_storageStats_wiredTiger_cache_bytes_dirty_in_the_cache_cumulative{job=\"$job\", instance=~\"$instance:9216\"}[1m])",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    },
    {
     "title": "cache pages requested from the cache",
     "type": "timeseries",
     "description": "Количество запросов страниц из кэша. Высокие значения указывают на хорошую эффективность кэша («в среднем за минуту» (скорость роста))",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 86 },
     "targets": [
      {
       "expr": "rate(mongodb_oplog_stats_storageStats_wiredTiger_cache_pages_requested_from_the_cache{job=\"$job\", instance=~\"$instance:9216\"}[1m])",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    },
    {
     "title": "wiredTiger currently in the cache",
     "type": "timeseries",
     "description": "Общий размер данных в кэше WiredTiger. Ключевой показатель эффективности кэширования.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "mongodb_oplog_stats_storageStats_wiredTiger_cache_bytes_currently_in_the_cache{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    },
    {
     "title": "WT fs read performance",
     "type": "timeseries",
     "description": "I/O задержки диска - read performance histogram, break by buckets («в среднем за минуту» (скорость роста))\nЕсли резко растут значения в bucket’ах 500ms+ или 1000ms+ → дисковая подсистема не справляется.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (perf_bucket)(rate(mongodb_ss_wt_perf{job=\"$job\", instance=~\"$instance:9216\", perf_bucket=~\"file system read latency histogram.*\"}[1m]))",
       "legendFormat": "state: {{perf_bucket}}"
      }
     ]
    },
    {
     "title": "WT fs write performance",
     "type": "timeseries",
     "description": "I/O задержки диска - write performance histogram, break by buckets («в среднем за минуту» (скорость роста))\nЕсли резко растут значения в bucket’ах 500ms+ или 1000ms+ → дисковая подсистема не справляется.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (perf_bucket)(rate(mongodb_ss_wt_perf{job=\"$job\", instance=~\"$instance:9216\", perf_bucket=~\"file system write latency histogram.*\"}[1m])) ",
       "legendFormat": "state: {{perf_bucket}}"
      }
     ]
    },
    {
     "title": "WT operation read performance",
     "type": "timeseries",
     "description": "внутренние READ задержки движка WiredTiger (конкуренция, блокировки, flush journal, компрессия и т. п.), break by buckets («в среднем за минуту» (скорость роста))\nЕсли резко растут значения в bucket’ах 500ms+ или 1000ms+ → дисковая подсистема не справляется.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (perf_bucket)(rate(mongodb_ss_wt_perf{job=\"$job\", instance=~\"$instance:9216\", perf_bucket=~\"operation read latency histogram.*\"}[1m])) ",
       "legendFormat": "state: {{perf_bucket}}"
      }
     ]
    },
    {
     "title": "WT operation write performance",
     "type": "timeseries",
     "description": "внутренние задержки движка WiredTiger (конкуренция, блокировки, flush journal, компрессия и т. п.) write performance histogram, break by buckets («в среднем за минуту» (скорость роста))\nЕсли резко растут значения в bucket’ах 500ms+ или 1000ms+ → дисковая подсистема не справляется.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (perf_bucket)(rate(mongodb_ss_wt_perf{job=\"$job\", instance=~\"$instance:9216\", perf_bucket=~\"operation write latency histogram.*\"}[1m])) ",
       "legendFormat": "state: {{perf_bucket}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB - Производительность и основные показатели (internal use)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collector scrape time",
     "type": "timeseries",
     "description": "Время сбора метрик различными коллекторами. Высокие значения могут указывать на проблемы производительности MongoDB или сети.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "collector_scrape_time_ms{collector=\"diagnostic_data\", job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "{{collector }} {{instance}}"
      },
      {
       "expr": "collector_scrape_time_ms{collector=\"top\", job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "{{collector }} {{instance}}"
      }
     ]
    },
    {
     "title": "Number of sorts in disk instead of memory",
     "type": "timeseries",
     "description": "метрика показывает сколько раз операции сортировки (sort) в MongoDB не смогли уложиться в выделенный лимит памяти и были вынуждены \"пролиться\" (spill) на диск («в среднем за минуту» (скорость роста))",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 111 },
     "targets": [
      {
       "expr": "rate(mongodb_ss_metrics_query_sort_spillToDisk{job=\"$job\", instance=~\"$instance:9216\"}[1m])",
       "legendFormat": "{{collector }} {{instance}}"
      },
      {
       "expr": "collector_scrape_time_ms{collector=\"top\", job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "{{collector }} {{instance}}"
      }
     ]
    },
    {
     "title": "mongodb asserts per second",
     "type": "timeseries",
     "description": "Количество утверждений (asserts) в MongoDB. Высокие значения указывают на внутренние ошибки или проблемы с данными.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 111 },
     "targets": [
      {
       "expr": "sum(rate(mongodb_asserts_total{type=\"user\", job=\"$job\", instance=~\"$instance:9216\"}[1m])) by (instance)",
       "legendFormat": "{{collector }} {{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_clusterTime_clusterTime{job=\"$job\", instance=~\"$instance:9216\"} * 1000",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB - Использование памяти и сборка мусора (internal use)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap alloc bytes",
     "type": "timeseries",
     "description": "Текущее использование heap-памяти экспортером. Резкий рост может указывать на утечку памяти.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    },
    {
     "title": "Heap in use bytes",
     "type": "timeseries",
     "description": "Размер heap-памяти, активно используемой экспортером.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    },
    {
     "title": "Idle bytes",
     "type": "timeseries",
     "description": "Размер неиспользуемой heap-памяти, которая может быть возвращена ОС.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    },
    {
     "title": "GC Duration",
     "type": "timeseries",
     "description": "Размер неиспользуемой heap-памяти, которая может быть возвращена ОС.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB - Эффективность индексов (internal use)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "number of indexes",
     "type": "timeseries",
     "description": "Количество индексов в коллекции. Слишком много индексов может замедлять запись.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 421 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mongodb_config_image_collection_stats_storageStats_nindexes{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    },
    {
     "title": "maximum tree depth",
     "type": "timeseries",
     "description": "Максимальная глубина B-дерева индекса. Большая глубина может снижать производительность поиска.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 421 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mongodb_config_image_collection_stats_storageStats_indexDetails_id_btree_maximum_tree_depth{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    },
    {
     "title": "_id index size",
     "type": "timeseries",
     "description": "Размер индекса _id. Базовый индекс, который есть в каждой коллекции.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 421 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "mongodb_config_image_collection_stats_storageStats_indexSizes_id{job=\"$job\", instance=~\"$instance:9216\"}",
       "legendFormat": "instance: {{instance}}, cl_id: {{cl_id}}"
      }
     ]
    }
   ]
  }
 ]
}