{
 "title": "Predictions",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"},instance)"
    }
   },
   { "name": "days", "query": "30d,90d" }
  ]
 },
 "panels": [
  {
   "title": "CPU Predicted in 30 Days",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "predict_linear((\n  sum by (instance) (\n    rate(node_cpu_seconds_total{mode!=\"idle\", job=\"$job\", instance=~\"$instance\"}[1h])\n  )\n  /\n  count by (instance) (\n    count(node_cpu_seconds_total{mode=\"idle\", job=\"$job\", instance=~\"$instance\"}) by (cpu, instance)\n  )\n)[14d:], $days )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk 30d prediction $job",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  predict_linear(\n    (node_filesystem_size_bytes{job=~\"$job\", instance=~\"$instance\",device!~\"tmpfs|loop.*|overlay|rootfs\"} - node_filesystem_avail_bytes{job=~\"$job\", instance=~\"$instance\",device!~\"tmpfs|loop.*|overlay|rootfs\"})[14d],\n    $days\n  )\n  * 100\n) / node_filesystem_size_bytes{job=~\"$job\", instance=~\"$instance\",device!~\"tmpfs|loop.*|overlay|rootfs\"} ",
     "legendFormat": "{{instance}}: {{ device}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Predict RAM $job",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - predict_linear(\n      node_memory_MemAvailable_bytes{instance=~\"$instance\", job=\"$job\"}[14d:], $days\n    )\n    /\n    node_memory_MemTotal_bytes{instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "usage {{ instance }}"
    }
   ]
  }
 ]
}