CREATE TABLE ATM_CTRL_TO_SITE_INSERT_LOG
(
   INSERT_DATE     DATE NOT NULL,
   INSERT_ROWS     NUMBER,
   INSERT_STATUS   VARCHAR2 (1000) DEFAULT 'SUCCESS'
)
TABLESPACE ANNUAL_TABLE
LOGGING
NOCOMPRESS;