CREATE TABLE DBMAN.ATM_ALPHA_TO_SITE_INSERT_LOG
(
  INSERT_DATE    DATE                           NOT NULL,
  INSERT_STATUS  VARCHAR2(1000 BYTE)            DEFAULT 'SUCCESS',
  INSERT_ROWS    NUMBER
)
TABLESPACE AF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
