CREATE TABLE ATM_ALPHA
(
   N_MRC_ATM                  NUMBER (5) NOT NULL,
   C_NATM                     VARCHAR2 (25) NOT NULL,
   C_ATM_SER_NUM              VARCHAR2 (20 BYTE),
   C_MRC_CITY_FULL            VARCHAR2 (4000 BYTE),
   C_MRC_ADDR_FULL            VARCHAR2 (4000 BYTE),
   C_MRC_CMP_NAME             VARCHAR2 (100 BYTE),
   C_ATM_TYPE                 VARCHAR2 (8 BYTE),
   CF_MRC_ATM_CASH_IN         VARCHAR2 (1 BYTE),
   CF_MRC_ATM_EUR             VARCHAR2 (1 BYTE),
   CF_MRC_ATM_USD             VARCHAR2 (1 BYTE),
   D_ATM_REG                  DATE,
   C_ATM_LOCATION_TYPE        VARCHAR2 (2 BYTE),
   C_ATM_LOCATION_TYPE_DESC   VARCHAR2 (4000 BYTE),
   C_ATM_AVAILABILITY         VARCHAR2 (4000 BYTE),
   CF_ATM_AVAILABILITY        VARCHAR2 (1 BYTE),
   C_ATM_ACCESSIBILITY        VARCHAR2 (4000 BYTE),
   CF_ATM_ACCESSIBILITY       VARCHAR2 (1 BYTE),
   CF_ATM_HANDICAP            VARCHAR2 (1 BYTE)
);

COMMENT ON COLUMN ATM_ALPHA.N_MRC_ATM IS 'код строки';
COMMENT ON COLUMN ATM_ALPHA.C_NATM IS 'номер ATM';
COMMENT ON COLUMN ATM_ALPHA.C_ATM_SER_NUM IS 'Серийный номер ATM';
COMMENT ON COLUMN ATM_ALPHA.C_MRC_CITY_FULL IS 'населенный пункт';
COMMENT ON COLUMN ATM_ALPHA.C_MRC_ADDR_FULL IS 'Полный адрес (без населенного пункта)';
COMMENT ON COLUMN ATM_ALPHA.C_MRC_CMP_NAME IS 'название компании';
COMMENT ON COLUMN ATM_ALPHA.C_ATM_TYPE IS 'тип ATM (Walk-In, VIP, OTD)';
COMMENT ON COLUMN ATM_ALPHA.CF_MRC_ATM_CASH_IN IS 'признак работы ATM c Cash-In (Y, N)';
COMMENT ON COLUMN ATM_ALPHA.CF_MRC_ATM_EUR IS 'признак работы ATM c EUR (Y, N)';
COMMENT ON COLUMN ATM_ALPHA.CF_MRC_ATM_USD IS 'признак работы ATM c USD (Y, N)';
COMMENT ON COLUMN ATM_ALPHA.D_ATM_REG IS 'дата регистрации мерчантов в Alpha/Prime';
COMMENT ON COLUMN ATM_ALPHA.C_ATM_LOCATION_TYPE IS 'тип расположения';
COMMENT ON COLUMN ATM_ALPHA.C_ATM_LOCATION_TYPE_DESC IS 'описание признака тип расположения';
COMMENT ON COLUMN ATM_ALPHA.C_ATM_AVAILABILITY IS 'описание признака время работы ATM';
COMMENT ON COLUMN ATM_ALPHA.CF_ATM_AVAILABILITY IS 'время работы ATM';
COMMENT ON COLUMN ATM_ALPHA.C_ATM_ACCESSIBILITY IS 'описание признака доступности для клиентов';
COMMENT ON COLUMN ATM_ALPHA.CF_ATM_ACCESSIBILITY IS 'доступность для клиентов';
COMMENT ON COLUMN ATM_ALPHA.CF_ATM_HANDICAP IS 'доступность для инвалидов';