DROP TABLE DBMAN.ATM_ALPHA_TEMP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE DBMAN.ATM_ALPHA_TEMP
(
  N_MRC_ATM                 NUMBER(5)           NOT NULL,
  C_NATM                    VARCHAR2(25 BYTE)   NOT NULL,
  C_ATM_SER_NUM             VARCHAR2(20 BYTE),
  C_MRC_CITY_FULL           VARCHAR2(4000 BYTE),
  C_MRC_ADDR_FULL           VARCHAR2(4000 BYTE),
  C_MRC_CMP_NAME            VARCHAR2(100 BYTE),
  C_ATM_TYPE                VARCHAR2(8 BYTE),
  CF_MRC_ATM_CASH_IN        VARCHAR2(1 BYTE),
  CF_MRC_ATM_EUR            VARCHAR2(1 BYTE),
  CF_MRC_ATM_USD            VARCHAR2(1 BYTE),
  D_ATM_REG                 DATE,
  C_ATM_LOCATION_TYPE       VARCHAR2(2 BYTE),
  C_ATM_LOCATION_TYPE_DESC  VARCHAR2(4000 BYTE),
  C_ATM_AVAILABILITY        VARCHAR2(4000 BYTE),
  CF_ATM_AVAILABILITY       VARCHAR2(1 BYTE),
  C_ATM_ACCESSIBILITY       VARCHAR2(4000 BYTE),
  CF_ATM_ACCESSIBILITY      VARCHAR2(1 BYTE),
  CF_ATM_HANDICAP           VARCHAR2(1 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE;
