STARTUP PFILE="c:\oracle\ora81\database\INITSLY.ora" NOMOUNT
CREATE CONTROLFILE REUSE SET DATABASE "SLY"
    MAXLOGFILES 20
    MAXLOGMEMBERS 5
    MAXDATAFILES 100
    MAXINSTANCES 10
    MAXLOGHISTORY 1018
LOGFILE
  GROUP 1 'D:\ORACLE\ORADATA\SLY\LOG01.REDO'  SIZE 16M REUSE,
  GROUP 2 'D:\ORACLE\ORADATA\SLY\LOG02.REDO'  SIZE 16M REUSE,
  GROUP 3 'D:\ORACLE\ORADATA\SLY\LOG03.REDO'  SIZE 16M REUSE RESETLOGS
DATAFILE
  'D:\ORACLE\ORADATA\SLY\SYSTEM01.DBF',
  'D:\ORACLE\ORADATA\SLY\SYSTEM02.DBF',
  'D:\ORACLE\ORADATA\SLY\RBS01.DBF',
  'D:\ORACLE\ORADATA\SLY\TOOLS01.DBF',
  'D:\ORACLE\ORADATA\SLY\DRSYS01.DBF',
  'D:\ORACLE\ORADATA\SLY\COMC_DAT01.DBF',
  'D:\ORACLE\ORADATA\SLY\COMC_IDX01.DBF',
  'D:\ORACLE\ORADATA\SLY\GK_DAT01.DBF',
  'D:\ORACLE\ORADATA\SLY\GK_IDX01.DBF',
  'D:\ORACLE\ORADATA\SLY\COMC_P0_DAT01.DBF',
  'D:\ORACLE\ORADATA\SLY\COMC_P1_DAT01.DBF',
  'D:\ORACLE\ORADATA\SLY\COMC_P2_DAT01.DBF'
CHARACTER SET CL8MSWIN1251
;

ALTER DATABASE OPEN RESETLOGS; 
ALTER TABLESPACE TEMP ADD TEMPFILE 'D:\ORACLE\ORADATA\SLY\TEMP01.DBF' REUSE;
