SPOOL unusable_idx_mov_out.txt
SET TIMING ON

ALTER INDEX IDX_AML_SUSPICIOUS REBUILD;
ALTER INDEX IX01_MCTB_CONTRACT_DATA REBUILD;
ALTER INDEX IX01_ACTB_MEM_ORDER_UNPRCD REBUILD;
ALTER INDEX IDX03_ACTB_MEM_ORDER REBUILD;
Elapsed: 00:00:00.26
SPOOL OFF
