--
-- Using Oracle's SYS_CONTEXT Function
--
SELECT 'ISDBA' NAME, SYS_CONTEXT('USERENV', 'ISDBA')     VALUE  FROM DUAL
UNION ALL
SELECT 'DB_NAME' NAME, SYS_CONTEXT('USERENV', 'DB_NAME')     VALUE  FROM DUAL
UNION ALL
SELECT 'DB_DOMAIN' NAME, SYS_CONTEXT('USERENV', 'DB_DOMAIN')     VALUE  FROM DUAL
UNION ALL
SELECT 'INSTANCE' NAME, SYS_CONTEXT('USERENV', 'INSTANCE')  VALUE   FROM DUAL
UNION ALL
SELECT 'LANGUAGE' NAME, SYS_CONTEXT('USERENV', 'LANGUAGE')  VALUE   FROM DUAL
UNION ALL
SELECT 'HOST' NAME, SYS_CONTEXT('USERENV', 'HOST')  VALUE  FROM DUAL
UNION ALL
SELECT 'TERMINAL' NAME, SYS_CONTEXT('USERENV', 'TERMINAL')  VALUE   FROM DUAL
UNION ALL
SELECT 'IP_ADDRESS' NAME, SYS_CONTEXT('USERENV','IP_ADDRESS') VALUE  FROM DUAL
UNION ALL
SELECT 'OS_USER' NAME, SYS_CONTEXT('USERENV','OS_USER') VALUE  FROM DUAL
UNION ALL
SELECT 'NETWORK_PROTOCOL' NAME, SYS_CONTEXT('USERENV', 'NETWORK_PROTOCOL')  VALUE  FROM DUAL
UNION ALL
SELECT 'EXTERNAL_NAME' NAME, SYS_CONTEXT('USERENV', 'EXTERNAL_NAME')  VALUE  FROM DUAL
UNION ALL
SELECT 'AUTHENTICATION_TYPE' NAME, SYS_CONTEXT('USERENV', 'AUTHENTICATION_TYPE')  VALUE  FROM DUAL
UNION ALL
SELECT 'AUTHENTICATION_DATA' NAME, SYS_CONTEXT('USERENV', 'AUTHENTICATION_DATA')  VALUE  FROM DUAL
UNION ALL
SELECT 'CURRENT_USER' NAME, SYS_CONTEXT('USERENV', 'CURRENT_USER')  VALUE  FROM DUAL
UNION ALL
SELECT 'CURRENT_SCHEMA' NAME, SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')  VALUE  FROM DUAL
UNION ALL
SELECT 'SESSION_ID' NAME, SYS_CONTEXT('USERENV', 'SESSIONID')  VALUE  FROM DUAL
UNION ALL
SELECT 'FG_JOB_ID' NAME, SYS_CONTEXT('USERENV', 'FG_JOB_ID')  VALUE  FROM DUAL
UNION ALL
SELECT 'BG_JOB_ID' NAME, SYS_CONTEXT('USERENV', 'BG_JOB_ID')  VALUE  FROM DUAL
/

SELECT 
  SYS_CONTEXT ( 'userenv', 'AUTHENTICATION_TYPE' ) authent
, SYS_CONTEXT ( 'userenv', 'CURRENT_SCHEMA' )      curr_schema
, SYS_CONTEXT ( 'userenv', 'CURRENT_USER' )        curr_user
, SYS_CONTEXT ( 'userenv', 'DB_NAME' )             db_name
, SYS_CONTEXT ( 'userenv', 'DB_DOMAIN' )           db_domain
, SYS_CONTEXT ( 'userenv', 'HOST' )                host
, SYS_CONTEXT ( 'userenv', 'IP_ADDRESS' )          ip_address
, SYS_CONTEXT ( 'userenv', 'OS_USER' )             os_user
FROM dual
/

